---
# Task4-/u03
# tasks file for diskrole
- name: check for user /u03
  stat:
    path: /u03
  register: user_check

- name: Get root filesystem usage
  shell: df -hP /u03 | tail -1
  register: disk_usage
  when: user_check.stat.exists == true

- name: Get hostname
  command: hostname
  register: host_name
  when: user_check.stat.exists == true

- debug:
    msg: '{{ disk_usage }}'
  when: user_check.stat.exists == true

- name: Extract disk usage percentage
  set_fact:
    root_used_percent: '{{ disk_usage.stdout.split()[4] | regex_replace(''%'','''') }}'
  when: user_check.stat.exists == true

- debug:
    msg: '{{ root_used_percent }}'
  when: user_check.stat.exists == true

- mail:
    host: '{{ smtp_host }}'
    port: '{{ smtp_port }}'
    subject: >-
      Alert: {{ host_name.stdout }} - {{ inventory_hostname }} - Disk usage is
      high
    body: |-
      Disk usage alert for {{ inventory_hostname }} 


       Host Name: {{ host_name.stdout }} 
       Usage: {{ root_used_percent }}% 


       Disk Space Usage Report:
       {{ disk_usage.stdout }}
    from: '{{ from_mail }}'
    to: '{{ to_mail }}'

  when: 
     - (root_used_percent | int) >= (u03_usage | int)
     - user_check.stat.exists == true
  ignore_errors: true
