---
# Task5-/u04
# tasks file for diskrole
- name: check for user /u04
  stat:
    path: /u04
  register: user_check

- shell: df -hP /u04
  register: disk_usage
  when: user_check.stat.exists == true
# ignore_errors: true
- debug: 
    msg: "{{ disk_usage.stdout_lines }}"
  when: user_check.stat.exists == true
- shell: df -hP /u04 | awk ' 0+$5 >= {{u04_usage}} {print $5}'|sed 's/%//g'
  register: disk
  when: user_check.stat.exists == true
- shell: hostname
  register: host_name
  when: user_check.stat.exists == true

- name: Send disk usage alert via AWS SNS
  command: >
    aws sns publish
    --topic-arn {{ sns_topic_arn }}
    --subject "Alert: {{ host_name.stdout }} - {{ inventory_hostname }} - Disk usage is high"
    --message "{{ sns_message }}"
  vars:
    sns_message: |
      Disk usage alert for {{ inventory_hostname }}
 
      Host Name: {{ host_name.stdout }}
      Mount Point: {{ disk_usage.stdout_lines[1].split()[5] }}
      Usage: {{ disk_usage.stdout_lines[1].split()[4] }}
 
      Disk Space Usage Report:
 
      {{ disk_usage.stdout_lines[0] }}
      {{ disk_usage.stdout_lines[1] }}
  when: disk.stdout | int >= root_usage
  ignore_errors: true