- name: List, sort Bamboo agents, and send notification

  hosts: localhost

  gather_facts: false
 
  vars_files:

    - names.yml
 
  tasks:

    - name: Get and sort Bamboo agents

      shell: |

        curl -s -u "{{ bamboo_username }}:{{ bamboo_password }}" \

          -H "Accept: application/json" \
https://bamboo.vitechinc.com/bamboo/rest/api/latest/agent?offline=false | \

        jq -r '.[] | select(.active == true and (.name | startswith("BAMBOO-OEL9") or startswith("VITECH"))) | .name' | \

        sort -t '-' -k4,4n | \

        nl -w 1 | \

        awk '{printf "%-6s %-60s\n", $1, $2}'

      register: bamboo_agents

      no_log: true
 
    - name: Format Bamboo agents into table

      set_fact:

        bamboo_table: |

          Index   Agent Name

          ------  ------------------------------------------------------------

          {{ bamboo_agents.stdout }}
 
    - name: Patching Email Notification via SNS

      community.aws.sns:

        topic: arn:aws:sns:us-east-1:389180911583:Testing

        subject: Bamboo Agents Patching

        msg: |

          Below Bamboo agents are going to be patched:
 
          {{ bamboo_table }}

      no_log: true

 
