---
- name: List, sort Bamboo agents, and send notification
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get Bamboo agents list and sort
      shell: |
        curl -H "Authorization: Bearer {{ bamboo_password }}" https://bamboo.vitechinc.com/bamboo/rest/api/latest/agent?offline=false | \
        jq -r '.[] | select(.active == true and (.name | startswith("BAMBOO-OEL9") or startswith("VITECH"))) | .name' | \
        sort -t '-' -k4,4n | \
        nl -w 1
      register: bamboo_agents
      no_log: false  # Setting no_log: false to print output in logs
      tags: get_agents

    - name: Display Bamboo agents output
      debug:
        msg: "Bamboo agents list: {{ bamboo_agents.stdout }}"
      tags: display_agents

    - name: Format Bamboo agents into HTML table format with darker border
      set_fact:
        bamboo_html_table: |
          <html>
          <body>
            <h3>Bamboo Agents to be Patched</h3>
            <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; font-family: Arial, sans-serif; border: 2px solid #333;">
              <tr style="background-color: #f2f2f2;">
                <th style="text-align: left; padding: 8px; border: 1px solid #333;">Index</th>
                <th style="text-align: left; padding: 8px; border: 1px solid #333;">Agent Name</th>
              </tr>
              {% for line in bamboo_agents.stdout_lines %}
              <tr style="background-color: {% if loop.index is odd %}#e0e0e0{% else %}#f7f7f7{% endif %};">
                <td style="text-align: left; padding: 8px; border: 1px solid #333;">{{ line.split()[0] }}</td>
                <td style="text-align: left; padding: 8px; border: 1px solid #333;">{{ line.split()[1:] | join(' ') }}</td>
              </tr>
              {% endfor %}
            </table>
          </body>
          </html>
      tags: format_table

    - name: Display formatted Bamboo agents HTML table
      debug:
        msg: "Formatted Bamboo agents HTML table:\n{{ bamboo_html_table }}"
      tags: display_table

    - name: Send Email Notification via SNS with HTML table
      community.aws.sns:
        topic: "arn:aws:sns:us-east-1:389180911583:Testing"
        subject: "Bamboo Agents Patching"
        msg: "{{ bamboo_html_table }}"
        message_structure: "html"
      no_log: false  # Set no_log: false to allow logging of this task output
      tags: send_notification

    - name: Confirm Email Notification Sent
      debug:
        msg: "Notification sent to SNS with topic: arn:aws:sns:us-east-1:389180911583:Testing"
      tags: confirm_notification
