---
- name: Update and reboot 
  hosts: all
  become: true
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
    sns_topic_arn: "arn:aws:sns:us-east-1:389180911583:Testing"  # Replace with your SNS Topic ARN
  tasks:
    - name: Check the kernel version before webserver patching
      shell: uname -r
      register: kversion

    - name: Get hostname
      shell: hostname
      register: hostname

    - name: Debug kernel version, hostname, and IP address
      debug:
        msg: |
          Hostname: {{ hostname.stdout }}
          IP Address: {{ ansible_default_ipv4.address }}
          Kernel Version: {{ kversion.stdout }}

    - name: Generate ASCII table for Kernel Version Details
      set_fact:
        table_output: |
          Kernel Version Details Before Patching
          
          +----+-------------------+-------------------------+-------------------------------------+
          | #  | IP Address        | Hostname                | Kernel Version                     |
          +----+-------------------+-------------------------+-------------------------------------+
          {% set serial_no = 1 %}
          {% for host in play_hosts %}
          | {{ serial_no }}  | {{ hostvars[host].ansible_default_ipv4.address }}     | {{ hostvars[host].hostname.stdout }}    | {{ hostvars[host].kversion.stdout }} |
          +----+-------------------+-------------------------+-------------------------------------+
          {% set serial_no = serial_no + 1 %}
          {% endfor %}
      tags:
        - generate_ascii_table

    - name: Send email with kernel version details using SNS (ASCII table format)
      run_once: true
      delegate_to: localhost
      community.aws.sns:
        region: "us-east-1"  # Replace with your AWS region
        topic: "{{ sns_topic_arn }}"
        msg: "{{ table_output }}"
        subject: "Before Patching Kernel Version Report"
      ignore_errors: yes

    - name: Pause for 180 seconds after upgrading packages
      pause:
        seconds: 360
