---
# tasks file for BAMBOOAGENETSPIPELINE
- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3
  gather_facts: no
  vars_files:
    - names.yml
  tasks:
      - name: Generate timestamp
        set_fact:
           timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
 
      - name: Debug the generated timestamp
        debug:
          msg: "Generated timestamp: {{ timestamp }}"
 
      - name: Debug VM names from vars file
        debug:
          msg: "VM names to snapshot: {{ vm_names }}"
 
      - name: Create snapshots for VMs in XAND DataCenter
        vmware_guest_snapshot:
          validate_certs: no
          hostname: "172.26.44.50"
          username: "{{ vcusername }}@vitechinc.com"
          password: "{{ vcpassword }}"
          datacenter: "{{ vcdc }}"
          folder: "/{{ vcdc }}/"
          name: "{{ item }}"
          state: present
          snapshot_name: "created_by_svallabhuni_{{ timestamp }}"
        register: out
        delegate_to: localhost
        with_items: "{{ vm_names }}"
      #  ignore_errors: true
      
      - name: Debug VM names from vars file
        debug:
          msg: "VM names to snapshot: {{ vm_names1 }}"

      - name: snapshots for NJ DATACENTER .....
        vmware_guest_snapshot:
          validate_certs: no
          hostname: "172.90.38.90"
          username: "{{ vcusername1 }}@vitechinc.com"
          password: "{{ vcpassword1 }}"
          datacenter: "{{ vcdc1 }}"
          folder: "/{{ vcdc1 }}/"
          name: "{{ item }}"    
          state: present
          snapshot_name: "creeated_by_svallabhuni_{{ timestamp }}"
      #    snapshot_name: backup
        register: snapshot_result
        delegate_to: localhost
        with_items: "{{ vm_names1 }}"
    #    ignore_errors: true
        
      - name: Debug snapshot results
        debug:
          var: snapshot_result
