
---
- hosts: all
  tasks:
  
#    - name: Start VM-BAMBOOPREPRD-TEST-AGENT.vitech.com
#      shell: |
#       source /home/bamboo/.bash_profile
#       /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
#      become: true 
#      become_user: bamboo  
#      when: ansible_host == '172.26.46.219'  # only run on specified host
      
    - name: start BAMBOO-OEL9-CLOUDAGNT-01-H.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.57.13'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-02.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.57.14'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-03.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.57.15'  # only run on specified host
      
    - name: start BAMBOO-OEL9-CLOUDAGNT-04.vitech.com 
      shell: 
        source /home/bamboo/.bash_profile    
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.52.172'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-05.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.52.173'  # only run on specified host

    - name: start BAMBOO-OEL9-CLOUDAGNT-06.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.52.174'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-07.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.52.163'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-08.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.52.169'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-09.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.52.170'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-10.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.52.171'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-11.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.45.88'  # only run on specified host
      ignore_errors: true


    - name: start BAMBOO-OEL9-CLOUDAGNT-12-H.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.48.231'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-13-H.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.47.142'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-14.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.56.19'  # only run on specified host


    - name: start BAMBOO-OEL9-CLOUDAGNT-15.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.52.167'  # only run on specified host


    - name: Start BAMBOO-OEL9-CLOUDAGNT-16.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.52.168'  # only run on specified host


    - name: Start BAMBOO-OEL9-CLOUDAGNT-17.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.56.16'  # only run on specified host


    - name: Start BAMBOO-OEL9-CLOUDAGNT-18.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.56.17'  # only run on specified host


    - name: Start BAMBOO-OEL9-CLOUDAGNT-19.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.56.18'  # only run on specified host
      ignore_errors: true


    - name: Start BAMBOO-OEL9-CLOUDAGNT-20.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.56.46'  # only run on specified host


    - name: Start BAMBOO-OEL9-CLOUDAGNT-21.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.56.47'  # only run on specified host


    - name: Start BAMBOO-OEL9-CLOUDAGNT-22.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.47.141'  # only run on specified host


    - name: Start BAMBOO-OEL9-CLOUDAGNT-23.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.56.15'  # only run on specified host

    - name: Start BAMBOO-OEL9-CLOUDAGNT-24.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.45.112'  # only run on specified host


    - name: Start BAMBOO-OEL9-CLOUDAGNT-25.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.45.113'  # only run on specified host


    - name: Start BAMBOO-OEL9-CLOUDAGNT-26.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.45.114'  # only run on specified host




    - name: Start VITECH-BAMBOO-SANAR-AGENT01.vitech.com
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true 
      become_user: bamboo 
      when: ansible_host == '10.172.2.180'  # only run on specified host
      

    - name: Pause for 180 seconds after upgrading packages
      pause:
        seconds: 360
        
    - name: Check the kernel version before webserver patching
      shell: uname -r
      register: kversion

    - name: Get hostname
      shell: hostname
      register: hostname

    - name: Debug kernel version, hostname, and IP address
      debug:
        msg: |
          Hostname: {{ hostname.stdout }}
          IP Address: {{ ansible_default_ipv4.address }}
          Kernel Version: {{ kversion.stdout }}

    - name: Send email with kernel version details in HTML table
      run_once: true
      delegate_to: localhost
      local_action:
        module: community.general.mail
        host: smtp-relay.vitech.com
        port: 25
        to: v3atlassianops@vitechinc.com
        subject: "After Patching Kernel Version Report"
        body: |
          <!DOCTYPE html>
          <html>
          <body>
            <h2>Kernel Version Details After Patching and bamboo agents </h2>
            <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse; width: 100%; text-align: left;">
              <thead>
                <tr style="background-color: #f2f2f2;">
                  <th>IP Address</th>
                  <th>Hostname</th>
                  <th>Kernel Version</th>
                </tr>
              </thead>
              <tbody>
                {% for host in play_hosts %}
                <tr>
                  <td>{{ hostvars[host].ansible_default_ipv4.address }}</td>
                  <td>{{ hostvars[host].hostname.stdout }}</td>
                  <td>{{ hostvars[host].kversion.stdout }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </body>
          </html>
        subtype: html
