
---
- hosts: all
  vars_files:
    - names.yml
  tasks:

    - name: Stop VM-BAMBOOPREPRD-TEST-AGENT.vitech.com
      shell:  /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh status
      become: true 
      become_user: bamboo  
      when:  ansible_host == '172.26.46.219'  # only run on specified host

  #  - name: Debug task output   
  #    debug: 
  #      var: stop_result

    - name: Stop BAMBOO-OEL9-CLOUDAGNT-01-H.vitech.com 
      shell: /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh status
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.57.13'  # only run on specified host


    - name: Stop BAMBOO-OEL9-CLOUDAGNT-02.vitech.com 
      shell: /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh status
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.57.14'  # only run on specified host
