---
- hosts: all
  tasks:   
    - name: start BAMBOO-OEL9-CLOUDAGNT-01-H.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.57.13'  # only run on specified host
