---
- hosts: all
  tasks:

    - name: Stop VM-BAMBOOPREPRD-TEST-AGENT.vitech.com
      shell:  /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh stop
      become: true
      become_user: bamboo
      when:  ansible_host == '172.26.46.219'

    - name: start BAMBOO-OEL9-CLOUDAGNT-01-H.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.57.13'  # only run on specified host

    - name: Debug password
      debug:
        msg: "Password is {{ ansible_ssh_pass | length }} characters long"

    - name: start BAMBOO-OEL9-CLOUDAGNT-02.vitech.com 
      shell: |
        source /home/bamboo/.bash_profile
        /u01/BambooCLOUDAGNT/bin/bamboo-agent.sh start
      become: true
      become_user: bamboo
      when: ansible_host == '172.26.57.14'  # only run on specified host
