---
- name: List, sort Bamboo agents, and send notification
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Use system Python or other interpreter

  tasks:
    - name: Ensure boto3 and botocore are installed
      pip:
        name:
          - boto3
          - botocore
      tags: install_python_libraries

    - name: Get Bamboo agents list and sort
      shell: |
        curl -H "Authorization: Bearer {{ bamboo_password }}" https://bamboo.vitechinc.com/bamboo/rest/api/latest/agent?offline=false | \
        jq -r '.[] | select(.active == true and (.name | startswith("BAMBOO-OEL9") or startswith("VITECH"))) 
      register: bamboo_agents
      no_log: false
      tags: get_agents

    - name: Display Bamboo agents output
      debug:
        msg: "Bamboo agents list: {{ bamboo_agents.stdout }}"
      tags: display_agents

    - name: Format Bamboo agents into table format
      set_fact:
        bamboo_table: |
          Index   Agent Name
          ------  ------------------------------------------------------------
          {{ bamboo_agents.stdout }}
      tags: format_table

    - name: Display formatted Bamboo agents table
      debug:
        msg: "Formatted Bamboo agents table:\n{{ bamboo_table }}"
      tags: display_table

    - name: Send Email Notification via SNS
      community.aws.sns:
        topic: "arn:aws:sns:us-east-1:389180911583:Testing"  # Replace with your SNS topic ARN
        subject: "Bamboo Agents Patching"
        msg: |
          Below Bamboo agents are going to be patched:
          {{ bamboo_table }}
      no_log: false  # Set no_log: false to allow logging of this task output
      tags: send_notification

    # Optional: Confirm notification sent (for debugging purposes)
    - name: Confirm Email Notification Sent
      debug:
        msg: "Notification sent to SNS with topic: arn:aws:sns:us-east-1:389180911583:Testing"
      tags: confirm_notification
