---
- hosts: Internal_Server
  gather_facts: yes
  tasks:
    - name: print starting date and time
      shell: date
      register: date_1

    - debug:
        msg: "{{ date_1.stdout }}"

    - shell: "shell_scripts/github_repo_names.sh"
      register: script_output
      environment:
        TOKEN: "{{ github_password }}"
        ORG_NAME: "{{ organization }}"
      become: false
