---
- hosts: Internal_Server
  gather_facts: yes
  vars:
    region: "us-west-2"
    path_00: "/u02/github_to_codecommit"
    path_01: "/u02/github_to_codecommit/github_clone"
    path_02: "/u02/github_to_codecommit/logs"
  tasks:
    - name: print starting date and time
      shell: date
      register: date_1

    - debug:
        msg: "{{ date_1.stdout }}"

    - name: Make github_repo_names.sh executable
      file:
        path: "../shell_scripts/github_repo_names_both.sh"
        mode: '0755'
        state: file

    - shell: "../shell_scripts/github_repo_names_both.sh"
      register: script_output
      environment:
        token_1: "{{ github_password_1 }}" 
        token_2: "{{ github_password_2 }}" 
        org_name_1: "{{ organization_1 }}"
        org_name_2: "{{ organization_2 }}"
      become: false

    - name: Parse JSON output from repo comparison script
      set_fact:
        repo_data: "{{ script_output.stdout | from_json }}"
 
    - name: Print repos in {{ organization_1 }}
      debug:
        msg: "{{ repo_data.vitechsystems_repos }}"
 
    - name: Print repos in {{ organization_2 }}
      debug:
       msg: "{{ repo_data.vitechinfra_repos }}"
 
    - name: Print common repos (in both orgs)
      debug:
        msg: "{{ repo_data.common_repos }}"
 
    - name: Print unique repos in {{ organization_2 }} (not in {{ organization_1 }})
      debug:
        msg: "{{ repo_data.filtered_repos }}"

    - name: filtering Nextgen and CoreAdmin from list
      set_fact: 
        filtered_vitechsystems_repos: "{{ repo_data.vitechsystems_repos | difference(['CoreAdmin', 'Nextgen']) }}"

    - debug:
        msg: "{{ filtered_vitechsystems_repos }}"

    - name: create a directory
      file: 
        path: "{{ path_00 }}"
        state: directory

    - name: create a directory
      file: 
        path: "{{ path_01 }}"
        state: directory

    - name: Clone GitHub Vitechsystems ORG repositories
      shell: |
        cd {{ path_01 }}
        if [ -d {{ item }}.git ]; then
          git -C {{ item }}.git remote update
        else
          git clone --mirror https://{{ github_username }}:{{ github_password_1 }}@github.com/{{ organization_1 }}/{{ item }}
        fi
      loop: "{{ repo_data.vitechsystems_repos }}" 
      register: git_clone_results_vitechsystems

    - name: Clone GitHub Vitechinfra ORG repositories
      shell: |
        cd {{ path_01 }}
        if [ -d {{ item }}.git ]; then
          git -C {{ item }}.git remote update
        else
          git clone --mirror https://{{ github_username }}:{{ github_password_2 }}@github.com/{{ organization_2 }}/{{ item }}
        fi
      loop: "{{ repo_data.filtered_repos }}" 
      register: git_clone_results_vitechinfra

    - name: Create CodeCommit repositories for vitechsystems 
      shell: aws codecommit create-repository --repository-name "{{ item }}" --region {{ region }} 
      register: codecommit_create_results_vitechsystems 
      with_items: "{{ repo_data.vitechsystems_repos }}"
      ignore_errors: yes

    - name: Newly created vitechsystems org repos on codecommit
      set_fact:
        codecommit_repo_names_vitechsystems: "{{ codecommit_repo_names_vitechsystems | default([]) + [item.item] | list }}"
      with_items: "{{ codecommit_create_results_vitechsystems.results }}"
      when: item.rc == 0
 
    - name: Display newly created vitechsystems org repositories
      debug:
        msg: "{{ codecommit_repo_names_vitechsystems }}"
      when: codecommit_repo_names_vitechsystems is defined

    - name: Push code to newly created vitechsystems org repositories on CodeCommit
      shell: |
        cp -r ../PYTHON_Script/incremental-repo-migration.py {{ path_01 }}/{{ item }}.git/
        cd {{ path_01 }}/{{ item }}.git
        git remote add codecommit https://{{ codecommit_username }}:{{ codecommit_password }}@git-codecommit.{{ region }}.amazonaws.com/v1/repos/{{ item }}
        python incremental-repo-migration.py
        git remote remove codecommit
      register: codecommit_first_push_result_vitechsystems
      when: codecommit_repo_names_vitechsystems is defined
      loop: "{{ codecommit_repo_names_vitechsystems }}"
      ignore_errors: yes

    - name: Send Notification on Success
      shell: |
        aws sns publish \
          --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
          --message "$(echo -e '**A New repositories have been added to AWS CodeCommit from Vitechsystems GitHub organization:**\n\n{{ codecommit_repo_names_vitechsystems }}\n\nPlease verify.\n\nThanks,\n\nv3atlassianops')" \
          --subject "New Vitechsystems Repositories Added To AWS CodeCommit"
      when:
        - codecommit_first_push_result_vitechsystems is defined
        - codecommit_first_push_result_vitechsystems.changed | default(false)

    - name: Create CodeCommit repositories for vitechinfra 
      shell: aws codecommit create-repository --repository-name "{{ item }}" --region {{ region }} 
      register: codecommit_create_results_vitechinfra 
      with_items: "{{ repo_data.filtered_repos }}"
      ignore_errors: yes

    - name: Newly created vitechinfra org repos on codecommit
      set_fact:
        codecommit_repo_names_vitechinfra: "{{ codecommit_repo_names_vitechinfra | default([]) + [item.item] | list }}"
      with_items: "{{ codecommit_create_results_vitechinfra.results }}"
      when: item.rc == 0
 
    - name: Display newly created vitechinfra org repositories
      debug:
        msg: "{{ codecommit_repo_names_vitechinfra }}"
      when: codecommit_repo_names_vitechinfra is defined

    - name: Push code to newly created vitechinfra org repositories on CodeCommit
      shell: |
        cp -r ../PYTHON_Script/incremental-repo-migration.py {{ path_01 }}/{{ item }}.git/
        cd {{ path_01 }}/{{ item }}.git
        git remote add codecommit https://{{ codecommit_username }}:{{ codecommit_password }}@git-codecommit.{{ region }}.amazonaws.com/v1/repos/{{ item }}
        python incremental-repo-migration.py
        git remote remove codecommit
      register: codecommit_first_push_result_vitechinfra
      when: codecommit_repo_names_vitechinfra is defined
      loop: "{{ codecommit_repo_names_vitechinfra }}"
      ignore_errors: yes

    - name: Send Notification on Success
      shell: |
        aws sns publish \
          --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
          --message "$(echo -e '**A New repositories have been added to AWS CodeCommit from Vitechinfra GitHub organization:**\n\n{{ codecommit_repo_names_vitechinfra }}\n\nPlease verify.\n\nThanks,\n\nv3atlassianops')" \
          --subject "New Vitechinfra Repositories Added To AWS CodeCommit"
      when:
        - codecommit_first_push_result_vitechinfra is defined
        - codecommit_first_push_result_vitechinfra.changed | default(false)
