---
- hosts: Internal_Server
  gather_facts: no
  vars:
    region: "us-west-2"
    path_00: "/u02/github_to_codecommit"
    sns_topic_arn: "arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd"
 
  tasks:
    - name: GitHub commits (vitechsystems)
      shell: git ls-remote https://{{ token_1 }}@github.com/vitechsystems/SIFO.git | awk '{print $1}' | head -n 1
      register: hello
      environment:
        token_1: "{{ github_password_1 }}" 

    - debug:
        msg: "{{ hello }}"

