---
# Tasks 
- name: Send Email Notification - Application is Up and Running
  ansible.builtin.shell: |
    aws sns publish \
      --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
      --message "$(echo -e "ERPPRD Patching Completed\n\n{{ app_hostname }} is up and running with:\n\nTomcat Version: apache-tomcat-{{ latest_tomcat_version }}\nAWS Corretto-8 Version: amazon-corretto-{{ latest_corretto_version }}\nIP Address: {{ app_ip }}\nHTTPS Status: {{ http_status.stdout }}\n\nTomcat Status: {{ tomcat_status.stdout }}")" \
      --subject "{{ app_hostname }} Application is Up and Running"
  args:
    executable: /bin/bash
  become: yes
  when: http_status.stdout == "200"
 
- name: Send Email Notification - Patching Failed
  ansible.builtin.shell: |
    aws sns publish \
      --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
      --message "$(echo -e "**Patching Failed** \n {{ app_hostname }} patching process failed. Tomcat did not return HTTPS 200.\nIP Address: {{ app_ip }}")" \
      --subject "{{ app_hostname }} Patching Failed"
  args:
    executable: /bin/bash
  become: yes
  when: http_status.stdout != "200"
 
- name: Fail the playbook if application is not running
  ansible.builtin.fail:
    msg: "Patching failed! The application is not responding with HTTP 200."
  when: http_status.stdout != "200"

