name: "Auto-Retry Dry Run PRs"

on:
  #schedule:
  #  - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:

jobs:
  dryrun-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1    

      - name: Run Org-Wide Dry-Run Script
        env:
          ORG_GITHUB_TOKEN: ${{ secrets.PROD_FINE_GRAINED_PAT }}
          MAX_RETRIES: 2
        run: python PYTHON_Script/auto_retry_prs_dryrun.py

