name: Bamboo agents stop
 
on:

  workflow_dispatch:

    inputs:

      KEY:

        description: "Authentication key"

        required: true

        type: string
 
env:

  RUNNER_NAME: "Internal_Tools_Automation_Server"

  INSTANCE_ID: "i-020530b54ac86537b"
 
jobs:

  start-runner:

    uses: vitechsystems/Internal-Tools_sub_workflows/.github/workflows/start_runner.yml@main

    secrets: inherit
 
  execute-job:

    name: Execute Job on Self-Hosted Runner

    needs: start-runner

    runs-on: Internal_Tools_Automation_Server
 
    steps:

      - name: Checkout repository

        uses: actions/checkout@v4
 
      - name: Set up AWS CLI

        uses: vitechsystems/configure-aws-credentials@v1.0

        with:

          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}

          aws-region: ${{ vars.AWS_REGION }}
 
      - name: Validate Authentication Key

        id: validate_key

        if: github.event_name == 'workflow_dispatch'

        run: |

          if [[ "${{ github.event.inputs.KEY }}" != "${{ secrets.OPS_INTERNAL_TOOLS_PASSWORD }}" ]]; then

            echo "Invalid authentication key."

            aws sns publish \

              --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \

              --message "$(echo -e "**Patching Aborted**\n\nInvalid authentication key provided.\n$(date +%Y-%m-%d)")" \

              --subject "Patching Aborted: Invalid Key"

            exit 1

          fi

      - name: Debug ansible_ssh_pass value
        run: echo "Password is:${{ secrets.ANSIBLE_SSH_PASS }}"

      - name: ✅ Print env variable (masked) - password length only

        run: |

          echo "Ansible password length is: ${#ANSIBLE_PASSWORD}"

          echo "Runner Name: $RUNNER_NAME"

          echo "Instance ID: $INSTANCE_ID"

        env:

          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_SSH_PASS }}

          RUNNER_NAME: ${{ env.RUNNER_NAME }}

          INSTANCE_ID: ${{ env.INSTANCE_ID }}
 
      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: |
          ansible-playbook Bamboo.agents/bamboo_stop.yml -i Bamboo.agents/inventory \
            --extra-vars "ansible_user=bamboo ansible_ssh_pass=$ANSIBLE_PASSWORD my_secure_pass=$ANSIBLE_PASSWORD"

#$'${{ secrets.INTERNAL_TOOLS_PASSWORD }}'$"

 
