name: Bamboo Agents Patching Pipeline
on:
  workflow_dispatch:
    inputs:
      KEY:
        description: 'Authentication Key for OPS Internal Tools'
        required: true
        type: string

env:
  RUNNER_NAME: "Internal_Tools_Automation_Server"
  INSTANCE_ID: "i-020530b54ac86537b"
 
jobs:
  start-runner:
    uses: vitechsystems/Internal-Tools_sub_workflows/.github/workflows/start_runner.yml@main
    with:
      runner_name: "Internal_Tools_Automation_Server"
    secrets: inherit
  
  execute-job:
    name: Execute Job on Self-Hosted Runner
    needs: start-runner
    runs-on: Internal_Tools_Automation_Server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up AWS CLI
        uses: vitechsystems/configure-aws-credentials@v1.0
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Validate Authentication Key
        id: validate_key
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ "${{ github.event.inputs.KEY }}" != "${{ secrets.OPS_INTERNAL_TOOLS_PASSWORD }}" ]]; then
            echo "Invalid authentication key."
            # Send notification for invalid key
            aws sns publish \
              --topic-arn arn:aws:sns:us-east-1:389180911583:Testing \
              --message "$(echo -e "**${{ github.event.inputs.APP_ENVIRONMENT }}-${{ github.event.inputs.APP_COMPONENT }} Patching Aborted**\n\nInvalid authentication key provided. Patching process was not started.\n$(date +%Y-%m-%d)")" \
              --subject "${{ github.event.inputs.APP_ENVIRONMENT }}-${{ github.event.inputs.APP_COMPONENT }} Patching Aborted: Invalid Key"
            exit 1
          fi



      - name: Send the Mail Notification 
        env:
          BAMBOO_PASSWORD: ${{ secrets.BAMBOO_PASSWORD }}
        run: |
          pwd
          ls -la
          sudo ansible-playbook BambooAgetns_patching/Agentstatusmail.yml --extra-vars "bamboo_password=${BAMBOO_PASSWORD}" -vvv
        continue-on-error: false

      - name: Run Ansible Playbook
        run: |
          ansible-playbook BambooAgetns_patching/stoptest.yml -i BambooAgetns_patching/Inventory_test.yml --extra-vars "ansible_password=${ANSIBLE_PASSWORD}" --ssh-extra-args="-o StrictHostKeyChecking=no"
        
   #   - name: Stop the System Service
  #      run: |
  #        pwd
  #        ls -la
  ##        sudo ansible-playbook Jenkins_Patching/stop.yaml -i $INVENTORY_PATH --extra-vars "url=${{ github.event.inputs.APP_COMPONENT }}"
  #      continue-on-error: false

  #    - name: Take System Snapshot
 #       run: |
  #        pwd
  #        ls -la
  #        sudo ansible-playbook Jenkins_Patching/snapshot.yml -i $INVENTORY_PATH1 \
  ##        --extra-vars "url=${{ github.event.inputs.APP_COMPONENT }}" \
   #       --extra-vars "vcusername=${{ vars.VC_USERNAME }}" \
   #       --extra-vars "vcpassword=${{ secrets.VC_PASSWORD }}" -vvv
   #     continue-on-error: false
        
   #   - name: Apply System Patches and Reboot
   #     run: |
   #       pwd
   #       ls -la
   #       sudo ansible-playbook Jenkins_Patching/PatchandReboot.yml -i $INVENTORY_PATH --extra-vars "url=${{ github.event.inputs.APP_COMPONENT }}"
   #     continue-on-error: false

    #  - name: Wait for 180 seconds
       # run: sleep 180

     # - name: Start the system service
     #   run: |
      #    pwd
       #   ls -la
       #   sudo ansible-playbook Jenkins_Patching/startandmail.yaml -i $INVENTORY_PATH --extra-vars "url=${{ github.event.inputs.APP_COMPONENT }}"
     #   continue-on-error: false
        
#  notify-on-failure:  # ✅ Now inside "jobs"
#    name: Send Failure Notification
#    needs: execute-job
#    if: ${{ always() && needs.execute-job.result == 'failure' }}  # Ensures it runs only if execute-job fails
#    runs-on: Internal_Tools_Automation_Server
#    steps:
#      - name: Set Inventory Path Again
#        run: echo "INVENTORY_PATH=Jenkins_Patching/inventory/${{ github.event.inputs.APP_ENVIRONMENT }}/${{ github.event.inputs.APP_COMPONENT }}/hosts" >> $GITHUB_ENV
 
#      - name: Debug Inventory Path
#        run: echo "Using INVENTORY_PATH=$INVENTORY_PATH"
 
#      - name: Send Failure Email
#        run: |
#          sudo ansible-playbook Jenkins_Patching/failure_notify.yaml -i $INVENTORY_PATH \
#          --extra-vars "app_component=${{ github.event.inputs.APP_COMPONENT }}"
          
  stop-runner:
    needs: execute-job
    uses: vitechsystems/Internal-Tools_sub_workflows/.github/workflows/stop_runner.yml@main
    with:
      runner_name: "Internal_Tools_Automation_Server"
    secrets: inherit
