name: Confluence Server Patching

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'The environment to patch (confluence or confluencedr)'   
      KEY:
        required: true
        description: Authentication Key for Confluence

jobs:
  Confluence-Patching:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write       

    steps:
      - name: Set environment-specific variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "confluencedr" ]; then
            echo "Using confluencedr configuration"
            echo "ASG_NAME=CONFLUENCEAWSDR-ConfluenceAWSPRODDScalingGroup-q2PbT1TX3oOj" >> $GITHUB_ENV
            echo "URL=https://confluencedr.vitechinc.com/confluencedr" >> $GITHUB_ENV
            echo "TOKEN=${{ secrets.confluencedr_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SNS_TOPIC=arn:aws:sns:us-west-2:389180911583:Internal-Tools_Patching" >> $GITHUB_ENV
            echo "SUBJECT_PREFIX=Restart of ConfluenceDR Nodes for Scheduled Patching" >> $GITHUB_ENV
            echo "BODY_PREFIX=ConfluenceDR patching is scheduled." >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "confluence" ]; then
                   if [ "${{ inputs.KEY }}" != "${{ secrets.VITECH_LINUX_ZOIO_PASSWORD }}" ]; then
                      echo "The KEY does not match the expected secret for confluence environment."
                      exit 1
                   fi
            echo "Using confluence configuration"
            echo "ASG_NAME=CONFLUENCEPROD-ConfluenceAWSPRODDScalingGroup-zAmOVDq6H2v8" >> $GITHUB_ENV
            echo "URL=https://confluence.vitechinc.com/confluence" >> $GITHUB_ENV
            echo "TOKEN=${{ secrets.confluence_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SNS_TOPIC=arn:aws:sns:us-east-1:389180911583:Internal-Tools_Patching" >> $GITHUB_ENV
            echo "SUBJECT_PREFIX=Restart of Confluence Nodes for Scheduled Patching" >> $GITHUB_ENV
            echo "BODY_PREFIX=Confluence patching is scheduled." >> $GITHUB_ENV  
          else
            echo "Invalid environment specified. Please choose either 'ConfluenceDR', or 'Confluence'."
            exit 1
          fi

      - name: Set AWS region
        run: |
          echo "AWS_REGION=${{ github.event.inputs.environment == 'confluence' && 'us-east-1' || 'us-west-2' }}" >> $GITHUB_ENV
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  

      - name: Send pre-patching notification via SNS
        run: |
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
            --query 'AutoScalingGroups[0].Instances[*].InstanceId' \
            --output text)

          if [[ -z "$INSTANCE_IDS" ]]; then
            echo "No instances found in the Auto Scaling Group. Exiting."
            exit 1
          fi
      
          aws sns publish \
            --topic-arn ${{ env.SNS_TOPIC }} \
            --subject "Rolling ${{ env.SUBJECT_PREFIX }}" \
            --message "$(printf "${{ env.BODY_PREFIX }} Please be aware of any disruptions during this process.\n\n **Instance IDs:**\n%s\n" "$INSTANCE_IDS")"

      - name: Get Auto Scaling Group Instances
        id: get-instances
        run: |
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
            --query 'AutoScalingGroups[0].Instances[*].InstanceId' \
            --output text | tr -s '\n' ' ')
          echo "INSTANCE_IDS=$INSTANCE_IDS" >> $GITHUB_ENV
          echo "Instance IDs: $INSTANCE_IDS"

      - name: Set Auto Scaling Group to 1 instances 
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
            --min-size 1 
            
      - name: Patch Each Instance
        id: patch-each-instance
        run: |
          INSTANCE_IDS_ARRAY=(${{ env.INSTANCE_IDS }})
          PATCH_SUCCESS=true  
      
          patch_instance() {
            local INSTANCE_ID=$1
            echo "Patching instance: $INSTANCE_ID"
      
            echo "Enter standby"
            aws autoscaling enter-standby \
              --auto-scaling-group-name "${{ env.ASG_NAME }}" \
              --instance-ids "$INSTANCE_ID" \
              --should-decrement-desired-capacity
      
            echo "Stop services, upgrade, and handle agent restart"
            run_ssm_command "$INSTANCE_ID" "Stop services" '["sudo service httpd stop", "sudo service confluence stop"]'
            run_upgrade "$INSTANCE_ID"
            run_ssm_command "$INSTANCE_ID" "Restart ds_agent" '["service ds_agent stop", "sleep 180", "sudo rmmod dsa_filter", "service ds_agent start"]'
      
            echo "Restart instance"
            restart_instance "$INSTANCE_ID"
            wait_for_ssm "$INSTANCE_ID"
      
            echo "Restart services"
            restart_services "$INSTANCE_ID"
      
            echo "Exit standby"
            aws autoscaling exit-standby \
              --auto-scaling-group-name "${{ env.ASG_NAME }}" \
              --instance-ids "$INSTANCE_ID"
      
            sleep 600
            verify_node_status "$INSTANCE_ID"
          }
      
          run_ssm_command() {
            local INSTANCE_ID=$1
            local COMMENT=$2
            local COMMANDS=$3
      
            aws ssm send-command \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --comment "$COMMENT" \
              --parameters "commands=$COMMANDS" \
              --query 'Command.CommandId' --output text > command-id.txt
      
            COMMAND_ID=$(cat command-id.txt)
            wait_for_command "$COMMAND_ID"
          }
      
          run_upgrade() {
            run_ssm_command "$1" "Upgrade Amazon Linux" '["dnf -y --releasever=latest update"]'
          }
      
          restart_instance() {
            local INSTANCE_ID=$1
            aws ec2 stop-instances --instance-ids "$INSTANCE_ID"
            aws ec2 wait instance-stopped --instance-ids "$INSTANCE_ID"
            aws ec2 start-instances --instance-ids "$INSTANCE_ID"
            aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
          }
      
          wait_for_ssm() {
            local INSTANCE_ID=$1
            for i in {1..30}; do
              STATUS=$(aws ssm describe-instance-information --filters "Key=InstanceIds,Values=$INSTANCE_ID" --query 'InstanceInformationList[0].PingStatus' --output text)
              [[ "$STATUS" == "Online" ]] && return
              echo "SSM not ready yet... waiting (attempt $i)"
              sleep 15
            done
            fail_workflow "$INSTANCE_ID" "SSM agent not ready"
          }
      
          wait_for_command() {
            local COMMAND_ID=$1
            for i in {1..30}; do
              COMMAND_STATUS=$(aws ssm list-commands --command-id "$COMMAND_ID" --query 'Commands[0].Status' --output text)
              echo "Current command status: $COMMAND_STATUS"
              [[ "$COMMAND_STATUS" == "Success" ]] && return
              [[ "$COMMAND_STATUS" == "Failed" ]] && fail_workflow "$INSTANCE_ID" "SSM command failed"
              sleep 30
            done
            fail_workflow "$INSTANCE_ID" "SSM command timeout"
          }
      
          restart_services() {
            run_ssm_command "$1" "Restart services" '["sudo cp -r /etc/httpd/conf.d /etc/httpd/conf.d.bak", "sudo service httpd restart", "sudo service confluence restart"]'
          }
      
          verify_node_status() {
            local INSTANCE_ID=$1
            INSTANCE_PRIVATE_IP=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" --query 'Reservations[].Instances[].PrivateIpAddress' --output text)
            NODE_STATUS=$(curl -X GET -H "Authorization: Bearer ${{ env.TOKEN }}" -H "Content-Type: application/json" "${{ env.URL }}/rest/zdu/cluster" | jq .)
            INSTANCE_ALIVE=$(echo "$NODE_STATUS" | jq --arg ip "$INSTANCE_PRIVATE_IP" '.nodes[] | select(.ipAddress == $ip and .state == "ACTIVE")')
            [[ -z "$INSTANCE_ALIVE" ]] && fail_workflow "$INSTANCE_ID" "Instance not healthy after patching"
          }
      
          send_sns_notification() {
            local INSTANCE_ID=$1
            local MESSAGE=$2
            aws sns publish --topic-arn ${{ env.SNS_TOPIC }} --subject "$MESSAGE for Instance $INSTANCE_ID" --message "$MESSAGE in ${{ github.event.inputs.environment }}. Please investigate."
          }
      
          fail_workflow() {
            local INSTANCE_ID=$1
            local ERROR_MESSAGE=$2
            send_sns_notification "$INSTANCE_ID" "$ERROR_MESSAGE"
            echo "Patching failed for instance $INSTANCE_ID: $ERROR_MESSAGE"
            exit 1
          }
      
          for INSTANCE_ID in "${INSTANCE_IDS_ARRAY[@]}"; do
            patch_instance "$INSTANCE_ID" || break
          done
      
          [[ "$PATCH_SUCCESS" == "false" ]] && exit 1
      
          echo "All instances patched successfully."

      - name: Set Auto Scaling Group to 2-2
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
            --min-size 2 

      - name: Check URL Status Code
        id: check_status
        run: |
          check_url_status() {
            local url=$1
            local max_attempts=3
            local delay=10
            local attempt=0
          
            while (( attempt < max_attempts )); do
              STATUS_CODE=$(curl --write-out "%{http_code}" --silent --output /dev/null "$url")
              echo "URL Status Code: $STATUS_CODE"
          
              if [[ "$STATUS_CODE" -eq 200 ]]; then
                echo "URL is up and running with status code 200"
                echo "status_code=200" >> $GITHUB_ENV
                return 0
              else
                echo "Attempt $((attempt + 1))/$max_attempts failed. Status Code: $STATUS_CODE"
                ((attempt++))
                sleep $delay
              fi
            done
          
            echo "Error: URL did not return status code 200 after $max_attempts attempts. Status Code: $STATUS_CODE"
            echo "status_code=$STATUS_CODE" >> $GITHUB_ENV
          
            aws sns publish \
              --topic-arn ${{ env.SNS_TOPIC }} \
              --subject "${{ github.event.inputs.environment }} App Down Alert - Status Code: $STATUS_CODE" \
              --message "The app at ${{ env.URL }} is down. Status code: $STATUS_CODE. Please investigate."
            exit 3
          }
          
          echo "Check the URL status"
          check_url_status "${{ env.URL }}/status"
          
          echo "Send notification if the status is healthy"
          if [[ "$status_code" -eq 200 ]]; then
            INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
              --auto-scaling-group-name "${{ env.ASG_NAME }}" \
              --query 'AutoScalingGroups[0].Instances[*].InstanceId' \
              --output text)
          
            MESSAGE="${{ env.BODY_PREFIX }} The patching has been completed successfully.
           **Patched Instance IDs:**
          $INSTANCE_IDS
          
          Please reach out to v3atlassianops@vitechinc.com for any issues."
          
            aws sns publish \
              --topic-arn ${{ env.SNS_TOPIC }} \
              --subject "Rolling ${{ env.SUBJECT_PREFIX }} Completed" \
              --message "$MESSAGE"
          else
            echo "Skipping post-patching notification due to failed URL status check."
          fi
