name: Confluence Server Patching

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'The environment to patch (confluence or confluencedr)'   
      KEY:
        required: true
        description: Authentication Key for Confluence

jobs:
  Confluence-Patching:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write       

    steps:
      - name: Set environment-specific variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "confluencedr" ]; then
            echo "Using confluencedr configuration"
            echo "ASG_NAME=CONFLUENCEAWSDR-ConfluenceAWSPRODDScalingGroup-q2PbT1TX3oOj" >> $GITHUB_ENV
            echo "URL=https://confluencedr.vitechinc.com/confluencedr" >> $GITHUB_ENV
            echo "TOKEN=${{ secrets.confluencedr_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SNS_TOPIC=arn:aws:sns:us-west-2:389180911583:Internal-Tools_Patching" >> $GITHUB_ENV
            echo "SUBJECT_PREFIX=Restart of ConfluenceDR Nodes for Scheduled Patching" >> $GITHUB_ENV
            echo "BODY_PREFIX=ConfluenceDR patching is scheduled." >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "confluence" ]; then
                   if [ "${{ inputs.KEY }}" != "${{ secrets.VITECH_LINUX_ZOIO_PASSWORD }}" ]; then
                      echo "The KEY does not match the expected secret for confluence environment."
                      exit 1
                   fi
            echo "Using confluence configuration"
            echo "ASG_NAME=CONFLUENCEPROD-ConfluenceAWSPRODDScalingGroup-zAmOVDq6H2v8" >> $GITHUB_ENV
            echo "URL=https://confluence.vitechinc.com/confluence" >> $GITHUB_ENV
            echo "TOKEN=${{ secrets.confluence_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SNS_TOPIC=arn:aws:sns:us-east-1:389180911583:Internal-Tools_Patching" >> $GITHUB_ENV
            echo "SUBJECT_PREFIX=Restart of Confluence Nodes for Scheduled Patching" >> $GITHUB_ENV
            echo "BODY_PREFIX=Confluence patching is scheduled." >> $GITHUB_ENV  
          else
            echo "Invalid environment specified. Please choose either 'ConfluenceDR', or 'Confluence'."
            exit 1
          fi

      - name: Set AWS region
        run: |
          if [ "${{ github.event.inputs.environment }}" == "confluence" ]; then
            echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          else
            echo "AWS_REGION=us-west-2" >> $GITHUB_ENV
          fi
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  

      - name: Send pre-patching notification via SNS
        run: |
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
            --query 'AutoScalingGroups[0].Instances[*].InstanceId' \
            --output text | tr -s '\n' ' ')
          
          if [[ -z "$INSTANCE_IDS" ]]; then
            echo "No instances found in the Auto Scaling Group. Exiting."
            exit 1
          fi
      
          aws sns publish \
            --topic-arn ${{ env.SNS_TOPIC }} \
            --subject "Rolling ${{ env.SUBJECT_PREFIX }}" \
            --message "${{ env.BODY_PREFIX }} Please be aware of any disruptions during this process. Instance IDs: $INSTANCE_IDS"

      - name: Get Auto Scaling Group Instances
        id: get-instances
        run: |
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
            --query 'AutoScalingGroups[0].Instances[*].InstanceId' \
            --output text | tr -s '\n' ' ')
          echo "INSTANCE_IDS=$INSTANCE_IDS" >> $GITHUB_ENV
          echo "Instance IDs: $INSTANCE_IDS"

      - name: Set Auto Scaling Group to 1 instances 
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
            --min-size 1 
            
      - name: Patch Each Instance
        id: patch-each-instance
        run: |
          INSTANCE_IDS_ARRAY=(${{ env.INSTANCE_IDS }})
          PATCH_SUCCESS=true  

          for INSTANCE_ID in "${INSTANCE_IDS_ARRAY[@]}"
          do
            echo "Patching instance: $INSTANCE_ID"

            aws autoscaling enter-standby \
              --auto-scaling-group-name "${{ env.ASG_NAME }}" \
              --instance-ids "$INSTANCE_ID" \
              --should-decrement-desired-capacity

            aws ssm send-command \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --comment "Stop confluence and HTTPD services" \
              --parameters 'commands=["sudo service httpd stop", "sudo service confluence stop"]'

            aws ssm send-command \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --comment "Upgrade to latest Amazon Linux release" \
              --parameters 'commands=["dnf -y --releasever=latest update"]' \
              --query 'Command.CommandId' --output text > command-id.txt
              COMMAND_ID=$(cat command-id.txt)
              echo "Waiting for upgrade command to complete..."
              for i in {1..30}; do
                  COMMAND_STATUS=$(aws ssm list-commands --command-id "$COMMAND_ID" --query 'Commands[0].Status' --output text)
                  echo "Current command status: $COMMAND_STATUS"     
                  if [[ "$COMMAND_STATUS" == "Success" ]]; then
                      echo "Command completed successfully."
                      break
                  elif [[ "$COMMAND_STATUS" == "Failed" ]]; then
                      echo "Command failed. Exiting..."
                      exit 1
                  fi
                  sleep 30  
              done              
              if [[ "$COMMAND_STATUS" != "Success" ]]; then
                  echo "Max attempts exceeded. Command did not complete."
                  exit 1
              fi

            echo "Stop the instance"
            aws ec2 stop-instances --instance-ids "$INSTANCE_ID"

            echo "Wait for the instance to stop"
            aws ec2 wait instance-stopped --instance-ids "$INSTANCE_ID"

            echo "Start the instance"
            aws ec2 start-instances --instance-ids "$INSTANCE_ID"

            echo "Wait for the instance to fully start"
            aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
            
            echo "Waiting for SSM agent to be ready..."
            SSM_READY=false
            for i in {1..30}; do
              STATUS=$(aws ssm describe-instance-information --filters "Key=InstanceIds,Values=$INSTANCE_ID" --query 'InstanceInformationList[0].PingStatus' --output text)
              if [[ "$STATUS" == "Online" ]]; then
                SSM_READY=true
                break
              fi
              echo "SSM not ready yet... waiting (attempt $i)"
              sleep 15
            done

            if [[ "$SSM_READY" == "false" ]]; then
              echo "SSM agent is not ready. Triggering SNS notification."
              aws sns publish \
                --topic-arn $SNS_TOPIC \
                --subject "SSM Not Ready for Instance $INSTANCE_ID" \
                --message "SSM agent did not become ready after EC2 start in "${{ github.event.inputs.environment }}" . Please investigate."
              exit 1
            fi

            # Check instance status, fail and trigger SNS if not running
            INSTANCE_STATE=$(aws ec2 describe-instance-status --instance-ids "$INSTANCE_ID" --query 'InstanceStatuses[0].InstanceState.Name' --output text)
            if [[ "$INSTANCE_STATE" != "running" ]]; then
              echo "Instance $INSTANCE_ID failed to start. Triggering SNS notification."
              aws sns publish \
                --topic-arn $SNS_TOPIC \
                --subject "EC2 Start Failure for Instance $INSTANCE_ID" \
                --message "Instance $INSTANCE_ID failed to start after "${{ github.event.inputs.environment }}" patching. Please investigate."
              exit 1
            fi

            aws ssm send-command \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --comment "Stop ds_agent remove dsa_filt and start ds_agent" \
              --parameters 'commands=["service ds_agent stop", "sleep 180", "sudo rmmod dsa_filter", "service ds_agent start"]'

            aws ssm send-command \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --comment "Backup /etc/httpd/conf.d, then restart confluence and HTTPD services" \
              --parameters 'commands=["sudo cp -r /etc/httpd/conf.d /etc/httpd/conf.d.bak", "sudo service httpd restart", "sudo service confluence restart"]'

            aws autoscaling exit-standby \
              --auto-scaling-group-name "${{ env.ASG_NAME }}" \
              --instance-ids "$INSTANCE_ID"

            sleep 600

            # Check node status using the API
            NODE_STATUS=$(curl -X GET \
              -H "Authorization: Bearer ${{ env.TOKEN }}" \
              -H "Content-Type: application/json" \
              "${{ env.URL }}/rest/zdu/cluster" | jq .)

            INSTANCE_PRIVATE_IP=$(aws ec2 describe-instances \
              --instance-ids "$INSTANCE_ID" \
              --query 'Reservations[].Instances[].PrivateIpAddress' \
              --output text)

            echo "Private IP: $INSTANCE_PRIVATE_IP"
            echo "NODE_STATUS: $NODE_STATUS"
            
            INSTANCE_ALIVE=$(echo "$NODE_STATUS" | jq --arg ip "$INSTANCE_PRIVATE_IP" '.nodes[] | select(.ipAddress == $ip and .state == "ACTIVE")')
            if [[ -n "$INSTANCE_ALIVE" ]]; then
              echo "Instance $INSTANCE_ID is alive and healthy."
              echo "========================================================="
            else
              echo "Error: Instance $INSTANCE_ID is NOT healthy. Sending notification."  
              aws sns publish \
                --topic-arn ${{ env.SNS_TOPIC }} \
                --subject "${{ env.SUBJECT_PREFIX }} Failed on Node $INSTANCE_PRIVATE_IP" \
                --message "Patching of instance $INSTANCE_ID ($INSTANCE_PRIVATE_IP) failed. Please investigate."
                
              PATCH_SUCCESS=false  
              break  
            fi
          done

          # Stop further patching if any instance failed
          if [[ "$PATCH_SUCCESS" == "false" ]]; then
            echo "Instances $INSTANCE_ID ($INSTANCE_PRIVATE_IP) failed the patching process. Exiting workflow."
            exit 1
          fi
          
      - name: Set Auto Scaling Group to 2-2
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
            --min-size 2 

      - name: Check URL Status Code
        id: check_status
        run: |
          STATUS_CODE=$(curl --write-out "%{http_code}" --silent --output /dev/null "${{ env.URL }}/status")
          echo "URL Status Code: $STATUS_CODE"
          if [[ "$STATUS_CODE" -eq 200 ]]; then
            echo "URL is up and running with status code 200"
            echo "status_code=200" >> $GITHUB_ENV
          else
            echo "Error: URL did not return status code 200. Status Code: $STATUS_CODE"
            echo "status_code=$STATUS_CODE" >> $GITHUB_ENV
            
            aws sns publish \
              --topic-arn ${{ env.SNS_TOPIC }} \
              --subject "${{ github.event.inputs.environment }} App Down Alert - Status Code: $STATUS_CODE" \
              --message "The app at ${{ env.URL }} is down. Status code: $STATUS_CODE. Please investigate."
            exit 3

          fi
         
      - name: Send post-patching notification via SNS
        if: env.status_code == '200'
        run: |
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
            --query 'AutoScalingGroups[0].Instances[*].InstanceId' \
            --output text | tr -s '\n' ' ')
      
          aws sns publish \
            --topic-arn ${{ env.SNS_TOPIC }} \
            --subject "Rolling ${{ env.SUBJECT_PREFIX }} Completed" \
            --message "${{ env.BODY_PREFIX }} The patching has been completed successfully, check URL: ${{ env.URL }}. Patched Instance IDs: $INSTANCE_IDS. Please reach out v3atlassianops@vitechinc.com for any issues."RL }}. Please reach out v3atlassianops@vitechinc.com for any issues."          
    
