name: Create Repository
on:
  workflow_dispatch:
    inputs:
      REPO_NAME:
        required: true
        description: Name to Create a New Repository (Eg:- VTHREEOPS_PRODUCT_L5)
      OWNER:
        required: true
        description: Repository type ('product' or 'client')
        default: 'client'
        type: choice
        options:
          - 'product'
          - 'client'

      PROJECT_KEY:
        required: true
        description: Jira Project Key
        
jobs:
  Check-Repository-type:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Repository type is valid
        run: |
          if [ "${{ inputs.OWNER }}" != "client" ] && [ "${{ inputs.OWNER }}" != "product" ]; then
            echo "Invalid Repository type value. Either it shoulb be 'product' or 'client' only. Stopping the workflow."
            exit 1
          fi
 
  Check-Repository-Existence:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: Check-Repository-type
    steps:
    - name: Check if Repository Exists
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" -X GET \
          -H "Authorization: token ${{ secrets.PROD_FINE_GRAINED_PAT }}" \
          "https://api.github.com/repos/vitechsystems/${{ inputs.REPO_NAME }}")
 
        if [ "$response" -eq "200" ]; then
          echo "Repository already exists. Stopping the workflow."
          exit 1
        fi
 
  Creating-Repository:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: Check-Repository-Existence
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Creating a New Repository then Adding all required permissions and configurtions. 
      run: |
          cd shell_scripts
          chmod +x git_repo_creation.sh
          ./git_repo_creation.sh ${{ secrets.PROD_FINE_GRAINED_PAT }} ${{ inputs.REPO_NAME }} ${{ inputs.OWNER }} ${{ inputs.PROJECT_KEY }} ${{ secrets.SECRET_CODE_GITHUB }}
          
    - name: Clear workspace
      run: |
        # Remove all files and directories in the workspace
        rm -rf *
