name: Create Repo Branch and Update Pom-files

on:
  workflow_dispatch:
    inputs:
      SOURCE_REPO_NAME:
        required: true
        description: Source Repo name
      TARGET_REPO_NAME:
        required: true
        description: Target Repo name
      confirm:
        default: "NO"
        required: true
        description: Specify 'YES' if client code should be in product code (COREADMIN/NEXTGEN), otherwise 'NO'.
      SOURCE_BRANCH:
        required: true
        description: Source branch name
      TARGET_BRANCH:
        required: true
        description: Target branch name
      SOURCE_CLIENT_VERSION:
        required: true
        description: Client Pom file version of source
      TARGET_CLIENT_VERSION:
        required: true
        description: Client Pom file version of target
      SOURCE_PROD_VERSION:
        required: false
        description: Prod Pom file version of source
      TARGET_PROD_VERSION:
        required: false
        description: Prod Pom file version of target
      Commit_Number:
        default: "HEAD"
        required: true
        description: SHA Value or default HEAD


jobs:
  create-branch-and-update-pom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate Inputs and Repository Type
        run: |
          if [ "${{ inputs.OWNER }}" != "client" ] && [ "${{ inputs.OWNER }}" != "product" ]; then
            echo "Invalid Repository type value '${{ inputs.OWNER }}'. Stopping the workflow."
            exit 1
          fi

          target_repo="${{ inputs.TARGET_REPO_NAME }}"
          confirm="${{ inputs.confirm }}"
          if [[ "$target_repo" == "Coreadmin" || "$target_repo" == "nextgen" ]]; then
            if [[ "$confirm" == "YES" ]]; then
              echo "Proceeding with target branch in product REPO COREADMIN/NEXTGEN"
            elif [[ "$confirm" == "NO" ]]; then
              echo "Not proceeding with target branch in product REPO COREADMIN/NEXTGEN"
              exit 0
            else
              echo "Invalid input for confirmation ('$confirm'). Please enter 'YES' or 'NO'."
              exit 2
            fi
          else
            echo "Invalid target repository type ('$target_repo'). Valid types are 'Coreadmin' and 'nextgen'."
            exit 1
          fi


      - name: Create and Push Branch
        run: |
          SOURCE_REPO_NAME="${{ inputs.SOURCE_REPO_NAME }}"
          TARGET_REPO_NAME="${{ inputs.TARGET_REPO_NAME }}"
          TARGET_REPO_NAME="${{ github.event.inputs.TARGET_REPO_NAME }}"
          SOURCE_BRANCH="${{ inputs.SOURCE_BRANCH }}"
          TARGET_BRANCH="${{ inputs.TARGET_BRANCH }}"
          SOURCE_CLIENT_VERSION="${{ inputs.SOURCE_CLIENT_VERSION }}"
          TARGET_CLIENT_VERSION="${{ inputs.TARGET_CLIENT_VERSION }}"
          SOURCE_PROD_VERSION="${{ inputs.SOURCE_PROD_VERSION }}"
          TARGET_PROD_VERSION="${{ inputs.TARGET_PROD_VERSION }}"
          COMMIT_NUMBER="${{ inputs.Commit_Number }}"
          
          set -x
          mkdir Branch_creation
          cd Branch_creation

          # Checking if the target branch already exists
          if git ls-remote --heads "https://${{ secrets.PROD_FINE_GRAINED_PAT }}@github.com/vitechsystems/${SOURCE_REPO_NAME}.git" $TARGET_BRANCH | grep -q $TARGET_BRANCH; then
            echo "Error: Branch $TARGET_BRANCH already exists. Please discard the existing one or create with a different name."
            exit 2
          else
            echo "Branch $TARGET_BRANCH doesn't exist. Proceeding with branch creation..."
          fi

          # Cloning the repository and checking out the source branch
          git clone "https://${{ secrets.PROD_FINE_GRAINED_PAT }}@github.com/vitechsystems/${SOURCE_REPO_NAME}.git" --single-branch --branch=$SOURCE_BRANCH
          cd $SOURCE_REPO_NAME

          # Checking out the target branch
          if [ "$COMMIT_NUMBER" = "HEAD" ]; then
            git checkout -b $TARGET_BRANCH
          else
            git checkout -b $TARGET_BRANCH $COMMIT_NUMBER
          fi

          # Pushing the newly created branch to the remote repository
          git config --local user.name "V3OPS_USER"
          git config --local user.email "v3ops@vitechinc.com"
          git remote set-url origin "https://${{ secrets.PROD_FINE_GRAINED_PAT }}@github.com/vitechsystems/${TARGET_REPO_NAME}.git"
          git push -u origin $TARGET_BRANCH

          # Checking if the branch was created successfully
          if git ls-remote --heads "https://${{ secrets.PROD_FINE_GRAINED_PAT }}@github.com/vitechsystems/${TARGET_REPO_NAME}.git" $TARGET_BRANCH | grep -q $TARGET_BRANCH; then
            echo "Branch $TARGET_BRANCH was created successfully."
            echo "Updating pom files and committing code..."

            # Updating pom files, committing and pushing changes
           echo "Updating pom.xml files..."
          find . -name pom.xml -exec sed -i 's/'"${SOURCE_CLIENT_VERSION}"'/'"${TARGET_CLIENT_VERSION}"'/g' {} +
          sleep 10
          find . -name pom.xml -exec sed -i 's/'"${SOURCE_PROD_VERSION}"'/'"${TARGET_PROD_VERSION}"'/g' {} +
            git add -u
            git commit -m "Updated pom files to version ${TARGET_CLIENT_VERSION}"
            git push -u origin $TARGET_BRANCH
          else
            echo "Error: Branch $TARGET_BRANCH was not created successfully."
            exit 3
          fi

      - name: Clean up workspace
        run: |
          rm -rf *
