name: "DATAREDENSION"
on:
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Push subfolder to AWS CodeCommit Velocity
        run: |
          ls -al
          git config --global user.name 'github-bamboo_vitech'
          git config --global user.email 'github-bamboo_vitech@vitechinc.com' # Use your email
          git clone https://${{ secrets.V3LOCITY_CODECOMMIT_USERNAME }}:${{ secrets.V3LOCITY_CODECOMMIT_PASSWORD }}@git-codecommit.us-west-2.amazonaws.com/v1/repos/dataretention.git
          ls -al
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Push subfolder to AWS CodeCommit Velocity
        run:
          git clone https://${{ secrets.V3LOCITY_CODECOMMIT_USERNAME }}:${{ secrets.V3LOCITY_CODECOMMIT_PASSWORD }}@git-codecommit.us-west-2.amazonaws.com/v1/repos/RetensionDBA
        #  git config --global user.name 'github-bamboo_vitech'
        #  git config --global user.password '${{ secrets.PROD_CLASSIC_PAT }}'
 #         git clone https://${{ secrets.V3LOCITY_CODECOMMIT_USERNAME }}:${{ secrets.V3LOCITY_CODECOMMIT_PASSWORD }}@git-codecommit.us-west-2.amazonaws.com/v1/repos/RetensionDBA
