name: "dataretention"
on:
  workflow_dispatch:

jobs:
  check_instances:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Open Web Client Directory
        run: |
          ls -la
          pwd
      - name: Navigate to folder
        run: cd PYTHON_Script
      - name: Open Web Client Directory
        run: |
          ls -la
          pwd
     # - name: Install AWS CLI
   #     run: |         
      #    sudo apt-get update         
      #    sudo apt-get install -y awscli
      - name: Configure Git
        run: |
         git remote add codecommit https://corpclouduserbot%40vitechinc.com-at-389180911583:CQM8iAdI133Xn6dc7B%2b30tX7Wcb6eGoAQdU%2bFuAXSXo%3d@git-codecommit.us-west-2.amazonaws.com/v1/repos/RetensionDBA
         git config --global credential.helper '!aws codecommit credential-helper $@'
         git config --global credential.UseHttpPath true
      - name: Push to AWS CodeCommit
        run: |
          git push -u codecommit main
      #- name: Create AWS CodeCommit Repository
       # run: |         
       # aws codecommit create-repository --repository-name skk --region us-west-2
      #- name: Configure AWS Credentials
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
       #   aws-access-key-id: ${{ V3LOCITY_CODECOMMIT_USERNAME }}
       #   aws-secret-access-key: ${{ V3LOCITY_CODECOMMIT_PASSWORD }}
       #   aws-region: us-west-2
 
