name: "dataretention"
on:
  workflow_dispatch:

jobs:
  check_instances:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Navigate to folder
        run: cd Internal-Tools/PYTHON_Script
