name: "dataretention"
on:
  workflow_dispatch:

jobs:
  check_instances:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Open Web Client Directory
        run: |
          ls -la
          pwd
      - name: Navigate to folder
        run: cd PYTHON_Script
      - name: Open Web Client Directory
        run: |
          ls -la
          pwd
