name: "dataretention_TK"
on:
  workflow_dispatch:
  
jobs:
  DBA_Retention:
    runs-on: ubuntu-latest
    steps:

      - name: Pushing the data retention folder to codecommit in Velocity Environment
        run: |
          cd /tmp
          git clone https://github-bamboo_vitech:${{ secrets.PROD_CLASSIC_PAT }}@github.com/vitechsystems/Internal-Tools.git
      - name: Pushing the data retention
        run: |
          cd /Internal-Tools
          git subtree push --prefix=PYTHON_Script https://${{ secrets.V3LOCITYDEV_CODECOMMIT_USERNAME }}:${{ secrets.V3LOCITYDEV_CODECOMMIT_PASSWORD }}@git-codecommit.us-west-2.amazonaws.com/v1/repos/dataretention_Velocity main
          
