name: "DATAREDENSION"

on:
  workflow_dispatch:

 
jobs:
  sync:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'github-bamboo_vitech'
          git config --global user.password '${{ secrets.PROD_CLASSIC_PAT }}'

      - name: Clone AWS CodeCommit repository
        run: |
          git clone https://${{ secrets.V3LOCITY_CODECOMMIT_USERNAME1 }}:${{ secrets.V3LOCITY_CODECOMMIT_PASSWORD1 }}@git-codecommit.us-west-2.amazonaws.com/v1/repos/RetensionDBA
          cd RetensionDBA
          git checkout main

      - name: Compare changes
        id: check_changes
        run: |
          cd ..
          if [ -z "$(git diff --name-only)" ]; then
            echo "No changes found."
            echo "skip" >> skip.txt
          else
            echo "Changes found."

      - name: Process the code based on comparison
        if: steps.check_changes.outputs.result != 'skip'
        run: |
          # Continue with your existing process here
          cd RetensionDBA
          rm -rf *
          cp -rf PYTHON_Script/* RetensionDBA/
          git add .
          git commit -m "Latest commits added"
          git push origin main
