name: "DATAREDENSION"
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: AWS code commit
        run: |
          ls -al
          git config --global user.name 'github-bamboo_vitech'
          
          git config --global user.password '${{ secrets.PROD_CLASSIC_PAT }}'
          git clone https://${{ secrets.V3LOCITY_CODECOMMIT_USERNAME1 }}:${{ secrets.V3LOCITY_CODECOMMIT_PASSWORD1 }}@git-codecommit.us-west-2.amazonaws.com/v1/repos/RetensionDBA
          ls -al
          pwd
          cd RetensionDBA
          ls -al
          rm -rf *
          ls -al
          cd ..
          ls -al
          cp -rf PYTHON_Script/* RetensionDBA/ 
          
          

 
      - name: Push subfolder to AWS CodeCommit Velocity
        run: |
          ls -al
          pwd
        #  git config --global user.name 'github-bamboo_vitech'
        #  git config --global user.password '${{ secrets.PROD_CLASSIC_PAT }}'
 #         git clone https://${{ secrets.V3LOCITY_CODECOMMIT_USERNAME }}:${{ secrets.V3LOCITY_CODECOMMIT_PASSWORD }}@git-codecommit.us-west-2.amazonaws.com/v1/repos/RetensionDBA
