name: ERPPRD-DR Patching Pipeline
on:
  workflow_dispatch:
    inputs:
      KEY:
        required: true
        description: Authentication Key for OPS Internal Tools
  schedule:
    # Every Monday at 11:00 AM EST (16:00 UTC)
    - cron: '0 16 * * 1'
 
jobs:
  run_on_last_saturday:
    if: github.event_name == 'schedule'
    uses: vitechsystems/Internal-Tools_sub_workflows/.github/workflows/time_last_saturday.yml@main
    with:
      run_type: monday_before_last_saturday
    secrets: inherit

  start-runner-scheduled:
    if: github.event_name == 'schedule' && needs.run_on_last_saturday.result == 'success' && needs.run_on_last_saturday.outputs.should_proceed == 'true'
    needs: run_on_last_saturday
    uses: vitechsystems/Internal-Tools_sub_workflows/.github/workflows/start_runner.yml@main
    with:
      runner_name: "Internal_Tools_Automation_Server"
    secrets: inherit
 
  start-runner-manual:
    if: github.event_name == 'workflow_dispatch'
    uses: vitechsystems/Internal-Tools_sub_workflows/.github/workflows/start_runner.yml@main
    with:
      runner_name: "Internal_Tools_Automation_Server"
    secrets: inherit
 
  execute-job-scheduled:
    needs: start-runner-scheduled
    runs-on: Internal_Tools_Automation_Server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up AWS CLI
        uses: vitechsystems/configure-aws-credentials@v1.0
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
 
      - name: Validate Authentication Key
        id: validate_key
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ "${{ inputs.KEY }}" != "${{ secrets.OPS_INTERNAL_TOOLS_PASSWORD }}" ]]; then
            echo "Invalid authentication key."
            # Send notification for invalid key
            aws sns publish \
              --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
              --message "$(echo -e "**ERPPRD-DR Patching Aborted**\n\nInvalid authentication key provided. Patching process was not started.\n\n$(date +%Y-%m-%d)")" \
              --subject "ERPPRD-DR Patching Aborted: Invalid Key"
            exit 1
          fi
 
      - name: Write defaults/main.yml file
        run: |
          sudo tee erpprd_patching/vars/main.yml > /dev/null <<EOF
          vcusername: "${{ vars.VC_USERNAME }}"
          vcpassword: "${{ secrets.VC_PASSWORD }}"
          EOF
 
      - name: Write inventory file
        run: |
          sudo tee erpprd_patching/tests/inventory > /dev/null <<EOF
          [DR]
          #VITECH-APP01-ERPPRD-DR-TOM9
          172.26.52.190 ansible_user=root ansible_ssh_pass="${{ secrets.VITECH_LINUX_ZOIO_PASSWORD }}"
          EOF
 
      - name: Run Ansible Playbook
        id: run_playbook
        run: |
          sudo ansible-playbook erpprd_patching/tests/test_2.yml -i erpprd_patching/tests/inventory
        continue-on-error: true  # Capture playbook failure but don't stop workflow
 
      - name: Check App Status with Curl
        id: check_app_status
        if: success()  # Only run if the playbook succeeded
        run: |
          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://v3.vitechinc.com/erp_dryrun/app)
          echo "Response Code: $RESPONSE_CODE"
          if [ "$RESPONSE_CODE" -eq 200 ]; then
            echo "APP_STATUS=up" >> $GITHUB_ENV
          else
            echo "APP_STATUS=down" >> $GITHUB_ENV
          fi
 
      - name: Send Notification on Playbook Failure
        if: steps.run_playbook.outcome == 'failure'
        run: |
          ERROR_MSG=$(grep -iE "fatal:|error:" $GITHUB_WORKSPACE/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/logs/*.log | tail -n 20)
          if [[ -z "$ERROR_MSG" ]]; then
            ERROR_MSG="No specific error message found. Check GitHub Actions logs for details."
          fi
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
            --message "$(echo -e "ERPPRD-DR Patch Status: FAILED\n\n **Error Details:**\n$ERROR_MSG\nPlease check the GitHub Actions logs for more details.\n\n\nAttention: ERPPRD_PROD will be undergoing a patch at this same time on the upcoming Saturday.\nPlease take action.")" \
            --subject "ERPPRD-DR Patching Failed"
 
      - name: Send Notification on Success
        if: steps.run_playbook.outcome == 'success' && env.APP_STATUS == 'up'
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
            --message "$(echo -e "**ERPPRD-DR Patch Status: SUCCESS**\n\nThe patching process for Tomcat has completed successfully.\nApplication is up and running with 200 status.\n$(date +%Y-%m-%d)\n\n\nAttention: ERPPRD_PROD will be undergoing a patch at this same time on the upcoming Saturday.")" \
            --subject "ERPPRD-DR Patching Completed"
 
      - name: Send Notification on App Down
        if: steps.run_playbook.outcome == 'success' && env.APP_STATUS == 'down'
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
            --message "$(echo -e "**Attention: ERPPRD-DR Patch Status: SUCCESS but App is Down**\nThe patching process has completed successfully, but the application is down. Please verify immediately.\n$(date +%Y-%m-%d)\n\n\nAttention: ERPPRD_PROD will be undergoing a patch at this same time on the upcoming Saturday.\nPlease take action.")" \
            --subject "ERPPRD-DR Patching Completed but App is Down"

      - name: Send Patch Notification Notification
        if: always()
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
            --message "$(echo -e "**Attention: ERPPRD_PROD will be undergoing a patch at this same time on the upcoming Saturday.**\n\nPlease take action.")" \
            --subject "ERPPRD-PROD Upcomming Patching Notification"

  execute-job-manual:
    needs: start-runner-manual
    runs-on: Internal_Tools_Automation_Server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up AWS CLI
        uses: vitechsystems/configure-aws-credentials@v1.0
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
 
      - name: Validate Authentication Key
        id: validate_key
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ "${{ inputs.KEY }}" != "${{ secrets.OPS_INTERNAL_TOOLS_PASSWORD }}" ]]; then
            echo "Invalid authentication key."
            # Send notification for invalid key
            aws sns publish \
              --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
              --message "$(echo -e "**ERPPRD-DR Patching Aborted**\n\nInvalid authentication key provided. Patching process was not started.\n\n$(date +%Y-%m-%d)")" \
              --subject "ERPPRD-DR Patching Aborted: Invalid Key"
            exit 1
          fi
 
      - name: Write defaults/main.yml file
        run: |
          sudo tee erpprd_patching/vars/main.yml > /dev/null <<EOF
          vcusername: "${{ vars.VC_USERNAME }}"
          vcpassword: "${{ secrets.VC_PASSWORD }}"
          EOF
 
      - name: Write inventory file
        run: |
          sudo tee erpprd_patching/tests/inventory > /dev/null <<EOF
          [DR]
          #VITECH-APP01-ERPPRD-DR-TOM9
          172.26.52.190 ansible_user=root ansible_ssh_pass="${{ secrets.VITECH_LINUX_ZOIO_PASSWORD }}"
          EOF
 
      - name: Run Ansible Playbook
        id: run_playbook
        run: |
          sudo ansible-playbook erpprd_patching/tests/test_2.yml -i erpprd_patching/tests/inventory
        continue-on-error: true  # Capture playbook failure but don't stop workflow
 
      - name: Check App Status with Curl
        id: check_app_status
        if: success()  # Only run if the playbook succeeded
        run: |
          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://v3.vitechinc.com/erp_dryrun/app)
          echo "Response Code: $RESPONSE_CODE"
          if [ "$RESPONSE_CODE" -eq 200 ]; then
            echo "APP_STATUS=up" >> $GITHUB_ENV
          else
            echo "APP_STATUS=down" >> $GITHUB_ENV
          fi
 
      - name: Send Notification on Playbook Failure
        if: steps.run_playbook.outcome == 'failure'
        run: |
          ERROR_MSG=$(grep -iE "fatal:|error:" $GITHUB_WORKSPACE/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/logs/*.log | tail -n 20)
          if [[ -z "$ERROR_MSG" ]]; then
            ERROR_MSG="No specific error message found. Check GitHub Actions logs for details."
          fi
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
            --message "$(echo -e "ERPPRD-DR Patch Status: FAILED\n\n **Error Details:**\n$ERROR_MSG\nPlease check the GitHub Actions logs for more details.\n\n\nAttention: ERPPRD_PROD will be undergoing a patch at this same time on the upcoming Saturday.\nPlease take action.")" \
            --subject "ERPPRD-DR Patching Failed"
 
      - name: Send Notification on Success
        if: steps.run_playbook.outcome == 'success' && env.APP_STATUS == 'up'
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
            --message "$(echo -e "**ERPPRD-DR Patch Status: SUCCESS**\n\nThe patching process for Tomcat has completed successfully.\nApplication is up and running with 200 status.\n$(date +%Y-%m-%d)\n\n\nAttention: ERPPRD_PROD will be undergoing a patch at this same time on the upcoming Saturday.")" \
            --subject "ERPPRD-DR Patching Completed"
 
      - name: Send Notification on App Down
        if: steps.run_playbook.outcome == 'success' && env.APP_STATUS == 'down'
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
            --message "$(echo -e "**Attention: ERPPRD-DR Patch Status: SUCCESS but App is Down**\nThe patching process has completed successfully, but the application is down. Please verify immediately.\n$(date +%Y-%m-%d)\n\n\nAttention: ERPPRD_PROD will be undergoing a patch at this same time on the upcoming Saturday.\nPlease take action.")" \
            --subject "ERPPRD-DR Patching Completed but App is Down"

  stop-runner:
    needs: [execute-job-scheduled, execute-job-manual]
    if: |
      needs.execute-job-scheduled.result != 'skipped' ||
      needs.execute-job-manual.result != 'skipped'
    uses: vitechsystems/Internal-Tools_sub_workflows/.github/workflows/stop_runner.yml@main
    with:
      runner_name: "Internal_Tools_Automation_Server"
    secrets: inherit
