name: GITGAS_Ruleset
 
on:

  # Allows the workflow to be triggered manually with inputs

  workflow_dispatch:

    inputs:

      ORG_NAME:

        description: 'Organization name (prod or client)'

        required: true

        default: 'prod'

      ORG:

        description: 'GitHub organization name'

        required: true

        default: 'Majesco-V3locity'

      REPOS:

        description: 'Repository name'

        required: true

        default: 'your-repo-name'
 
jobs:

  create-ruleset:

    runs-on: ubuntu-24.04

    steps:

    - name: Check out repository

      uses: actions/checkout@v4
 
    - name: Change directories and execute script

      env:

        GITHUB_TOKEN: ${{ secrets.MAJESCO_CLASSIC_PAT }}

        ORG_NAME: ${{ github.event.inputs.ORG_NAME }}

        ORG: ${{ github.event.inputs.ORG }}

        REPOS: ${{ github.event.inputs.REPOS }}

      run: |

        ls -al

        cd shell_scripts

        ls -al

        chmod +x ./GITGHAS.sh

        ./GITGHAS.sh $ORG_NAME $ORG $REPOS
