name: Renaming Branch
on:
  workflow_dispatch:
    inputs:
      REPO_NAME:
        required: true
        description: Name of the Repository
      EXISTING_BRANCH_NAME:
        required: true
        description: EXISTING_BRANCH_NAME
      NEW_BRANCH_NAME:
        required: true
        description: NEW_BRANCH_NAME
        
jobs:
  Check-Repository-type_And_Branch-Name:
    runs-on: arc-codeql-runners
    steps:
      - name: Check if its a default branch
        run: |
          if [ "${{ inputs.EXISTING_BRANCH_NAME }}" = "main" ]; then
            echo "Default branch (main) cannat be changed. Stopping the workflow."
            exit 1
          fi
          
  Check-Branch-Existence:
    runs-on: arc-codeql-runners
    permissions:
      id-token: write
      contents: read
    needs: Check-Repository-type_And_Branch-Name
    steps:
    - name: Check if Branch Exists
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" -X GET \
          -H "Authorization: token ${{ secrets.PROD_FINE_GRAINED_PAT }}" \
          "https://api.github.com/repos/vitechsystems/${{ inputs.REPO_NAME }}/branches/${{ inputs.EXISTING_BRANCH_NAME }}")
 
        if [ "$response" -eq "404" ]; then
          echo "Branch is not exists. Stopping the workflow."
          exit 1
        fi
        
  Renaming-Git-Branch:
    runs-on: arc-codeql-runners
    permissions:
      id-token: write
      contents: write
    needs: Check-Branch-Existence
    steps:
      
    - name: Changing Branch name for Repo-${{ inputs.REPO_NAME }}
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.PROD_FINE_GRAINED_PAT }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/vitechsystems/${{ inputs.REPO_NAME }}/branches/${{ inputs.EXISTING_BRANCH_NAME }}/rename \
        -d '{"new_name":"${{ inputs.NEW_BRANCH_NAME }}"}'
