name: Fetch GitHub Billing Usage

on:
  workflow_dispatch:

jobs:
  fetch-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Process Usage for Multiple Organizations
        run: |
          total_usage=0

          declare -A ORG_PAT=(
            [vitechsystems]="${{ secrets.PROD_FINE_GRAINED_PAT }}"
            [VitechInfra]="${{ secrets.INFRA_FINE_GRAINED_PAT }}"
          )

          for ORG in vitechsystems VitechInfra; do
            echo "Fetching usage for organization: $ORG"

            response=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${ORG_PAT[$ORG]}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/organizations/$ORG/settings/billing/usage")

            echo "$response" > "$ORG-usage.json"
            cat "$ORG-usage.json"

            #org_total=$(jq '[.usageItems[]? | select((.product | ascii_downcase) == "actions" and (.unitType | ascii_downcase) == "minutes") | .quantity // 0] | add' "$ORG-usage.json")
            org_total=$(jq '[.usageItems[]? | select((.product | ascii_downcase) == "actions" and (.unitType | ascii_downcase) == "minutes") ] | group_by(.sku) | map(map(.quantity // 0) | add) | add' "$ORG-usage.json")
            echo "Total Minutes Used for $ORG: $org_total minutes"

            echo "${ORG^^}_TOTAL_MINUTES_USED=$org_total" >> $GITHUB_ENV  # Store separately

            total_usage=$((total_usage + org_total))
          done

          echo "Grand Total Minutes Used: $total_usage minutes"
          echo "TOTAL_MINUTES_USED=$total_usage" >> $GITHUB_ENV

      - name: Print Individual and Grand Total Usage
        run: |
          echo "Total minutes used in vitechsystems: ${{ env.VITECHSYSTEMS_TOTAL_MINUTES_USED }}"
          echo "Total minutes used in VitechInfra: ${{ env.VITECHINFRA_TOTAL_MINUTES_USED }}"
          echo "Grand total minutes used: ${{ env.TOTAL_MINUTES_USED }}"
