name: TEST_Mirror GitHub Repos to AWS CodeCommit
 
on:
  workflow_dispatch:
 
jobs:
  start-runner:
    uses: vitechsystems/Internal-Tools_sub_workflows/.github/workflows/start_runner.yml@main
    secrets: inherit

  GitHub_Backup:
    name: Run Ansible Playbook
    needs: start-runner
    runs-on: Internal_Tools_Automation_Server
 
    env:
      path_00: /u02/github_to_codecommit
      path_01: /u02/github_to_codecommit/github_clone
      path_02: /u02/github_to_codecommit/logs
      github_username: github-bamboo_vitech
      github_password: ${{ secrets.PROD_FINE_GRAINED_PAT }}
      organization: vitechsystems
      region: us-west-2
      codecommit_username: ${{ secrets.CODECOMMIT_USERNAME }}
      codecommit_password: ${{ secrets.CODECOMMIT_PASSWORD }}
      smtp_host: smtp-relay.vitech.com
      smtp_port: '25'
      from_mail: v3opsinternal@vitechinc.com
      to_mail: v3atlassianops@vitechinc.com
 
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
 
      - name: Run Ansible Playbook
        run: |
          ansible-playbook Ansible/github_backup_1.yml
