name: TEST_Mirror GitHub Repos to AWS CodeCommit
 
on:
  workflow_dispatch:
 
jobs:
  GitHub_Backup:
    name: Run Ansible Playbook
    runs-on: Internal_Tools_Automation_Server
 
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
 
      - name: Run Ansible Playbook
        run: |
          sudo ansible-playbook Ansible/github_backup_1.yml -i Ansible/inventory -e "github_username=github-bamboo_vitech github_password_1=${{ secrets.PROD_FINE_GRAINED_PAT }} organization_1=vitechsystems github_password_2=${{ secrets.INFRA_FINE_GRAINED_PAT }} organization_2=vitechinfra path_00=/u02/github_to_codecommit path_01=/u02/github_to_codecommit/github_clone path_02=/u02/github_to_codecommit/logs"
