name: Print GitHub Secret in Python
 
on:
  workflow_dispatch:
 
jobs:
  print-secret:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Run Python script with secret
        run: python3 PYTHON_Script/script.py
        env:
          SECRET_CODE_GITHUB: ${{ secrets.SECRET_CODE_GITHUB }}
