name: Fetch and Notify GitHub Runner Usage

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the 1st of every month
  workflow_dispatch:    # Allows manual trigger

jobs:
  fetch-usage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch and Process Runner Usage Data
        run: |
          echo "Fetching GitHub Actions runner usage..."
          #GITHUB_API_URL="https://api.github.com/orgs/VitechInfra/actions/usage"
          GITHUB_API_URL="https://api.github.com/orgs/vitechsystems/settings/billing/actions"
          #RESPONSE=$(curl -H "Authorization: Bearer ${{ secrets.PROD_FINE_GRAINED_PAT }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "$GITHUB_API_URL")


           QUERY='{ "query": "query { organization(login: \"VitechInfra\") { actionsUsage(period: PREVIOUS_MONTH) { totalMinutesUsed totalPaidMinutesUsed minutesUsedBreakdown { UBUNTU MACOS WINDOWS total } } } }" }'


          RESPONSE=$(curl -X POST https://api.github.com/graphql \
            -H "Authorization: Bearer ${{ secrets.PROD_FINE_GRAINED_PAT }}" \
            -H "Content-Type: application/json" \
            --data "$QUERY")

                        
          echo "Full API Response:"
          echo "$RESPONSE" | jq .
          echo "$RESPONSE" > runner_usage.json

          SELF_HOSTED_MINUTES=$(echo "$RESPONSE" | jq '.billable."SELF_HOSTED".total_ms // 0')
          HOSTED_MINUTES=$(echo "$RESPONSE" | jq '.billable."GITHUB_HOSTED".total_ms // 0')

          SELF_HOSTED_MINUTES=$(jq '.billable."SELF_HOSTED".total_ms // 0' runner_usage.json)
          HOSTED_MINUTES=$(jq '.billable."GITHUB_HOSTED".total_ms // 0' runner_usage.json)

          SELF_HOSTED_MINUTES=$((SELF_HOSTED_MINUTES / 60000))
          HOSTED_MINUTES=$((HOSTED_MINUTES / 60000))

          echo "GitHub Actions Usage Summary:" 
          echo "--------------------------------------"
          echo "Self-hosted Runner Minutes: $SELF_HOSTED_MINUTES"
          echo "GitHub-hosted Runner Minutes: $HOSTED_MINUTES"

     
      - name: Upload Usage Data as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runner-usage-data
          path: runner_usage.json
