name: Check Sync between GitHub And AWS CodeCommit Repositories
 
on:
  workflow_dispatch:
 
jobs:
  GitHub_Backup:
    runs-on: Internal_Tools_Automation_Server_2
    
    env:
      GITHUB_TOKEN_1: ${{ secrets.PROD_FINE_GRAINED_PAT }}
      GITHUB_TOKEN_2: ${{ secrets.INFRA_FINE_GRAINED_PAT }}
      GITHUB_USERNAME: github-bamboo_vitech
      CODECOMMIT_USERNAME: ${{ secrets.AWS_CODECOMMIT_USERNAME }}
      CODECOMMIT_PASSWORD: ${{ secrets.AWS_CODECOMMIT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install boto3 requests python-dateutil

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run GitHub runner monitor script
        run: python3 PYTHON_Script/github_backup_sync_mail.py
 
