name: Jira Report Issues Export & Email
 
on:
  workflow_dispatch:
    inputs:
      jira_project:
        description: 'Optional: Jira project key (used only if no JQL is provided)'
        required: false
      duration_months:
        description: 'Optional: Number of months to look back (used only if no JQL is provided)'
        required: false
      jira_jql:
        description: 'Optional: Full JQL query (overrides project + duration)'
        required: false
 
jobs:
  run-report:
    runs-on: ubuntu-latest
    env:
      JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      JIRA_PROJECT: ${{ github.event.inputs.jira_project }}
      DURATION_MONTHS: ${{ github.event.inputs.duration_months }}
      JIRA_JQL: ${{ github.event.inputs.jira_jql }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
 
      - name: Install Python dependencies
        run: |
          pip install jira boto3
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
 
      - name: Run Jira Report Script
        run: python3 PYTHON_Script/JIRA_PROJECT_ISSUES.py
