name: Generate JIRA Dupms

env:
  JIRA_INSTANCE_ID_1: i-0701b695cf611c383
  JIRA_INSTANCE_ID_2: i-0d78aecfd23d2d10c

on:
  workflow_dispatch:
    inputs:
      KEY:
        required: true
        description: Authentication Key for OPS Internal Tools

jobs:
  jira_dumps:
    name: Creating JIRA Dupms
    runs-on: ubuntu-24.04
    steps:       
      - name: Set up AWS CLI
        uses: vitechsystems/configure-aws-credentials@v1.0
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Validate Authentication Key
        id: validate_key
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ "${{ inputs.KEY }}" != "${{ secrets.OPS_INTERNAL_TOOLS_PASSWORD }}" ]]; then
            echo "Invalid authentication key."
            # Send notification for invalid key
            aws sns publish \
              --topic-arn arn:aws:sns:us-east-1:389180911583:VitechToolsNVAProd \
              --message "$(echo -e "**JIRA Dump Generation Aborted**\n\nInvalid authentication key provided. JIRA Dump Generation process is not started.\n$(date +%Y-%m-%d)")" \
              --subject "JIRA Dump Generation Aborted: Invalid Key"
            exit 1
          fi

      - name: Run Command on EC2 Instance to generate dumps and send to mail on Jira node 1
        run: |
          aws ssm send-command \
            --instance-ids ${{ env.JIRA_INSTANCE_ID_1 }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands='sudo /u01/jira_dump.sh' \
            --region ${{ vars.AWS_REGION }} > /tmp/command_output_1.json
          COMMAND_ID_1=$(jq -r '.Command.CommandId' < /tmp/command_output_1.json)
          echo "COMMAND_ID_1=$COMMAND_ID_1" >> $GITHUB_ENV

      - name: Run Command on EC2 Instance to generate dumps and send to mail on Jira node 2
        run: |
          aws ssm send-command \
            --instance-ids ${{ env.JIRA_INSTANCE_ID_2 }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands='sudo /u01/jira_dump.sh' \
            --region ${{ vars.AWS_REGION }} > /tmp/command_output_2.json
          COMMAND_ID_2=$(jq -r '.Command.CommandId' < /tmp/command_output_2.json)
          echo "COMMAND_ID_2=$COMMAND_ID_2" >> $GITHUB_ENV
 
      - name: Verify script execution with retries on Jira node ${{ env.JIRA_INSTANCE_ID_1 }} 
        run: |
          END_TIME=$(( $(date +%s) + 5000 )) # 5000 seconds timeout
          while [ $(date +%s) -lt $END_TIME ]; do
            STATUS=$(aws ssm list-command-invocations \
              --command-id ${{ env.COMMAND_ID_1 }} \
              --details \
              --query "CommandInvocations[0].Status" \
              --output text)
            if [ "$STATUS" == "Success" ]; then
              echo "Shell script executed successfully!"
              break
            elif [ "$STATUS" == "Failed" ]; then
              echo "Shell script execution failed."
              exit 1
            else
              echo "Shell script not yet successful. Retrying in 100 seconds..."
              sleep 100
            fi
          done
 
      - name: Verify script execution with retries on Jira node ${{ env.JIRA_INSTANCE_ID_2 }} 
        run: |
          END_TIME=$(( $(date +%s) + 5000 )) # 5000 seconds timeout
          while [ $(date +%s) -lt $END_TIME ]; do
            STATUS=$(aws ssm list-command-invocations \
              --command-id ${{ env.COMMAND_ID_2 }} \
              --details \
              --query "CommandInvocations[0].Status" \
              --output text)
            if [ "$STATUS" == "Success" ]; then
              echo "Shell script executed successfully!"
              break
            elif [ "$STATUS" == "Failed" ]; then
              echo "Shell script execution failed."
              exit 1
            else
              echo "Shell script not yet successful. Retrying in 100 seconds..."
              sleep 100
            fi
          done
