name: Jira server Patching

on:
  workflow_dispatch:
    inputs:
      pluginKeys:
        description: 'Comma-separated plugin keys to disable'
        required: true
        default: 'com.vitechinc.jira.hoursTracking,com.vitechinc.jira.defaultCommentSecurity,com.vitechinc.art.ArtJiraService'

jobs:
  update-instance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Send pre-patching notification via SNS
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:389180911583:Internal-Tools_Patching \
            --subject "JirauPG is going down for patching - Rolling" \
            --message "This is a notification that Jiraupg is scheduled for patching. Please be aware of any disruptions during this process."    

      - name: Disable Jira Plugins
        run: |
          PLUGIN_KEYS="${{ github.event.inputs.pluginKeys }}"
          for PLUGIN_KEY in $(echo $PLUGIN_KEYS | tr "," "\n")
          do
            echo "Disabling plugin: $PLUGIN_KEY"
            curl --request PUT "https://jiraupg.vitechinc.com/jiraupg/rest/plugins/1.0/${PLUGIN_KEY}-key" \
                 --header 'Authorization: Bearer ${jiraupg_ACCESS_TOKEN}' \
                 --header 'Content-Type: application/vnd.atl.plugins.plugin+json' \
                 --data '{"enabled": false}'
          done

      - name: Get Auto Scaling Group Instances
        id: get-instances
        run: |
          ASG_NAME="JIRAUPG-JIRAAWSUPGADScalingGroup-mAS5ealzU5Lc"
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-name "$ASG_NAME" \
            --query 'AutoScalingGroups[0].Instances[*].InstanceId' \
            --output text | tr -s '\n' ' ')
          echo "INSTANCE_IDS=$INSTANCE_IDS" >> $GITHUB_ENV
          echo "Instance IDs: $INSTANCE_IDS"
      
          if [[ -z "$INSTANCE_IDS" ]]; then
            echo "Error: No instances found in the Auto Scaling Group. Exiting."
            exit 1
          fi

      - name: Set Auto Scaling Group to 1-2 instances 
        run: |
          ASG_NAME="JIRAUPG-JIRAAWSUPGADScalingGroup-mAS5ealzU5Lc"
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name "$ASG_NAME" \
            --min-size 1 \
            --max-size 2 

      - name: Patch Instance 1
        id: patch-instance-1
        run: |
          INSTANCE_IDS_ARRAY=(${{ env.INSTANCE_IDS }})
          INSTANCE_TO_PATCH=${INSTANCE_IDS_ARRAY[0]}
          echo "Patching instance: $INSTANCE_TO_PATCH"

          aws autoscaling enter-standby \
            --auto-scaling-group-name "JIRAUPG-JIRAAWSUPGADScalingGroup-mAS5ealzU5Lc" \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --should-decrement-desired-capacity

          aws ssm send-command \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --document-name "AWS-RunShellScript" \
            --comment "Restart Jira and HTTPD services" \
            --parameters 'commands=["sudo service jira stop"]'  

          aws ssm send-command \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --document-name "AWS-RunShellScript" \
            --comment "Upgrade to latest Amazon Linux release" \
            --parameters 'commands=["LATEST_VERSION=\$(curl -s https://docs.aws.amazon.com/linux/al2023/release-notes/ | grep -oP \\\"Version \\\K[0-9\.]+(?=:)\\\") && sudo dnf upgrade --releasever=\$LATEST_VERSION -y"]'

          aws ssm send-command \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --document-name "AWS-RunShellScript" \
            --comment "Restart instance" \
            --parameters 'commands=["sudo reboot"]'

          sleep 120

          aws ssm send-command \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --document-name "AWS-RunShellScript" \
            --comment "Restart Jira and HTTPD services" \
            --parameters 'commands=["sudo service httpd restart", "sudo service jira restart"]'

          echo "Jira health check passed on instance $INSTANCE_TO_PATCH"

          aws autoscaling exit-standby \
            --auto-scaling-group-name "JIRAUPG-JIRAAWSUPGADScalingGroup-mAS5ealzU5Lc" \
            --instance-ids "$INSTANCE_TO_PATCH"

          # Check node status using the API
          NODE_STATUS=$(curl -X GET \
            -H "Authorization: Bearer ${jiraupg_ACCESS_TOKEN}" \
            -H "Content-Type: application/json" \
            "https://jiraupg.vitechinc.com/jiraupg/rest/api/2/cluster/nodes" | jq .)

          INSTANCE_IDS_ARRAY=(${{ env.INSTANCE_IDS }})
          INSTANCE_TO_PATCH_PRIVATE_IP=$(aws ec2 describe-instances --instance-ids ${INSTANCE_IDS_ARRAY[0]} --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text)
  
          INSTANCE_ALIVE=$(echo "$NODE_STATUS" | jq --arg ip "$INSTANCE_TO_PATCH_PRIVATE_IP" '.[] | select(.ip == $ip and .alive == true)')
  
          if [[ -n "$INSTANCE_ALIVE" ]]; then
            echo "Instance ${INSTANCE_IDS_ARRAY[0]} is alive and healthy."
          else
            echo "Error: Instance ${INSTANCE_IDS_ARRAY[0]} is NOT healthy. Sending notification."
  
            aws sns publish \
              --topic-arn arn:aws:sns:us-east-1:389180911583:Internal-Tools_Patching \
              --subject "JirauPG Patching Failed (Instance 1)" \
              --message "Patching of instance ${INSTANCE_IDS_ARRAY[0]} failed. Please investigate."
  
            exit 1 
          fi  

      - name: Patch Instance 2
        if: needs.patch-instance-1.result == 'success'
        id: patch-instance-2
        run: |
          INSTANCE_IDS_ARRAY=(${{ env.INSTANCE_IDS }})
          INSTANCE_TO_PATCH=${INSTANCE_IDS_ARRAY[1]}
          echo "Patching instance: $INSTANCE_TO_PATCH"

          aws autoscaling enter-standby \
            --auto-scaling-group-name "JIRAUPG-JIRAAWSUPGADScalingGroup-mAS5ealzU5Lc" \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --should-decrement-desired-capacity
         
          aws ssm send-command \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --document-name "AWS-RunShellScript" \
            --comment "Restart Jira and HTTPD services" \
            --parameters 'commands=["sudo service jira stop"]' 
            
          aws ssm send-command \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --document-name "AWS-RunShellScript" \
            --comment "Upgrade to latest Amazon Linux release" \
            --parameters 'commands=["LATEST_VERSION=\$(curl -s https://docs.aws.amazon.com/linux/al2023/release-notes/ | grep -oP \\\"Version \\\K[0-9\.]+(?=:)\\\") && sudo dnf upgrade --releasever=\$LATEST_VERSION -y"]'

          aws ssm send-command \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --document-name "AWS-RunShellScript" \
            --comment "Restart instance" \
            --parameters 'commands=["sudo reboot"]'

          sleep 120

          aws ssm send-command \
            --instance-ids "$INSTANCE_TO_PATCH" \
            --document-name "AWS-RunShellScript" \
            --comment "Restart Jira and HTTPD services" \
            --parameters 'commands=["sudo service httpd restart", "sudo service jira restart"]'

          echo "Jira health check passed on instance $INSTANCE_TO_PATCH"

          aws autoscaling exit-standby \
            --auto-scaling-group-name "JIRAUPG-JIRAAWSUPGADScalingGroup-mAS5ealzU5Lc" \
            --instance-ids "$INSTANCE_TO_PATCH"

          # Check node status using the API
          NODE_STATUS=$(curl -X GET \
            -H "Authorization: Bearer ${jiraupg_ACCESS_TOKEN}" \
            -H "Content-Type: application/json" \
            "https://jiraupg.vitechinc.com/jiraupg/rest/api/2/cluster/nodes" | jq .)

          INSTANCE_IDS_ARRAY=(${{ env.INSTANCE_IDS }})
          INSTANCE_TO_PATCH_PRIVATE_IP=$(aws ec2 describe-instances --instance-ids ${INSTANCE_IDS_ARRAY[0]} --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text)
  
          INSTANCE_ALIVE=$(echo "$NODE_STATUS" | jq --arg ip "$INSTANCE_TO_PATCH_PRIVATE_IP" '.[] | select(.ip == $ip and .alive == true)')
  
          if [[ -n "$INSTANCE_ALIVE" ]]; then
            echo "Instance ${INSTANCE_IDS_ARRAY[0]} is alive and healthy."
          else
            echo "Error: Instance ${INSTANCE_IDS_ARRAY[0]} is NOT healthy. Sending notification."
  
            aws sns publish \
              --topic-arn arn:aws:sns:us-east-1:389180911583:Internal-Tools_Patching \
              --subject "JirauPG Patching Failed (Instance 2)" \
              --message "Patching of instance ${INSTANCE_IDS_ARRAY[0]} failed. Please investigate."
  
            exit 2 
          fi
            

      - name: Set Auto Scaling Group to 2-2
        run: |
          ASG_NAME="JIRAUPG-JIRAAWSUPGADScalingGroup-mAS5ealzU5Lc"
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name "$ASG_NAME" \
            --min-size 2 \
            --max-size 2 
            
      - name: Enable Jira Plugins
        run: |
            PLUGIN_KEYS="${{ github.event.inputs.pluginKeys }}"
            for PLUGIN_KEY in $(echo $PLUGIN_KEYS | tr "," "\n")
            do
              echo "Disabling plugin: $PLUGIN_KEY"
              curl --request PUT "https://jiraupg.vitechinc.com/jiraupg/rest/plugins/1.0/${PLUGIN_KEY}-key" \
                   --header 'Authorization: Bearer ${jiraupg_ACCESS_TOKEN}' \
                   --header 'Content-Type: application/vnd.atl.plugins.plugin+json' \
                   --data '{"enabled": true}'
            done
            
      - name: Send post-patching notification via SNS
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:389180911583:Internal-Tools_Patching \
            --subject "Rolling Patching Completed for Jiraupg" \
            --message "The patching for Jiraupg has been completed successfully. If any issues arise, please reach out to v3atlassianops@vitechinc.com. Thanks for your patience during this process."     
