name: Runner Stats Collection

on:
  workflow_dispatch:

jobs:
  collect-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Runner Usage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ORGS=("vitechsystems" "VitechInfra") # List of organizations
          echo "Organization,Repository,Run ID,Duration" > usage_report.csv

          for ORG in "${ORGS[@]}"; do
            REPO_LIST=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/orgs/$ORG/repos?per_page=100" | jq -r '.[].full_name')

            for REPO in $REPO_LIST; do
              RUNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO/actions/runs")

              RUN_IDS=$(echo $RUNS | jq -r '.workflow_runs[].id')
              for RUN_ID in $RUN_IDS; do
                TIMING=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                  "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/timing")

                DURATION=$(echo $TIMING | jq '.total_duration' | awk '{print $1/60}') # Convert seconds to minutes
                echo "$ORG,$REPO,$RUN_ID,$DURATION" >> usage_report.csv
              done
            done
          done

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: usage-report
          path: usage_report.csv
