name: "Runners Status"

on:
  workflow_dispatch:

jobs:
  LaunchingSelfHostedRunner:
    runs-on: ubuntu-latest
    outputs:
      genrun: ${{ steps.gen_step.outputs.INSTANCE_ID }}      # <== Note the output variable
    steps:      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
