name: "Runners Status"

on:
  workflow_dispatch:

jobs:

  check_instances:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout code

        uses: actions/checkout@v2
 
      - name: Set up Python

        uses: actions/setup-python@v2

        with:

          python-version: '3.x'
 
      - name: Install dependencies

        run: pip install boto3 requests
 
      - name: Run EC2 Instance Checker

        env:

          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}

        run: python3 Pythonrunner.py   # Replace with the actual filename of your Python script

