name: "Testing_Runners_Status"

on:
  schedule:
    - cron: '30,40,50 15 12 8 *'  # 15:30,15:40,15:50 UTC (10:30-10:50 AM EST)
    - cron: '*/10 16 12 8 *'      # every 10 min from 16:00 to 16:50 UTC (11:00-11:30 AM EST)

  workflow_dispatch:

jobs:
  check_instances:
    runs-on: ubuntu-latest
    
    env:
      CLASSIC_PAT: ${{ secrets.CLASSIC_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
 
      - name: Install dependencies
        run: pip install boto3 requests

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CORP_CLD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORP_CLD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - run: python3 PYTHON_Script/TESting_runners.py
