name: Time Test
on:
  workflow_dispatch:
  schedule:
    - cron: "50 13 * * 1"  # Runs every Saturday at 03:00 AM UTC (10:00 PM EST Of FRIDAY)
 
env:
  RUNNER_NAME: "Internal_Tools_Automation_Server"
  INSTANCE_ID: "i-020530b54ac86537b"
 
jobs:
  run_on_last_saturday: 
    if: github.event_name == 'schedule'  # Only runs for scheduled trigger 
    uses: vitechsystems/github-runner-testing/.github/workflows/time_test.yml@main 
    with: 
      run_type: 2nd_last_saturday 
    secrets: inherit 
 
  # Dummy job to satisfy the 'needs' dependency for workflow_dispatch 
  dummy_for_dispatch: 
    if: github.event_name == 'workflow_dispatch'  # Only runs for manual trigger 
    runs-on: ubuntu-latest 
    steps: 
      - name: Dummy Step 
        run: echo "This is a dummy job to satisfy the dependency for workflow_dispatch." 
 
  start-runner: 
    needs: [run_on_last_saturday, dummy_for_dispatch]  # Depends on both jobs 
    uses: vitechsystems/service_workflows/.github/workflows/start_runner.yml@main 
    secrets: inherit
