name: 'wiz-cli'

on:
  workflow_dispatch:
    inputs:
      repo_name:
        type: string
        description: 'Org/Repository_Name to scan'
      branch_name:
        type: string
        description: 'Branch_name to scan'

jobs:
  wiz-cli-iac-scan:
    name: 'Wiz-cli Iac Scan'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      POLICY: "Default IaC policy"

    steps:
      - name: Check out specific repository and branch 
        run: |
           echo "Cloning repository and checking out source branch $SOURCE_BRANCH..."
           git clone "https://${{ secrets.PROD_CLASSIC_PAT }}@github.com/${{ inputs.repo_name }}.git" --single-branch --branch=${{ inputs.branch_name }}
           REPO_DIR=$(basename ${{ inputs.repo_name }})  
           
      - name: Download Wiz CLI
        run: |
          curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 &&
          chmod +x wizcli

      - name: Authenticate to Wiz
        run: |
          ./wizcli auth --id "${{ secrets.WIZ_CLIENT_ID }}" --secret "${{ secrets.WIZ_CLIENT_SECRET }}"
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Run wiz CLI IaC scan 
        run: ./wizcli iac scan --path "./$REPO_DIR" --policy "$POLICY"
