name: 'wiz-cli'

on:
  workflow_dispatch:
    inputs:
      repo_name:
        type: string
        description: 'The URL of the repository to scan'
      branch_name:
        type: string
        description: 'The branch to checkout and scan'

jobs:
  wiz-cli-iac-scan:
    name: 'Wiz-cli Iac Scan'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      POLICY: "Default lac policy"

    steps:
      - name: Check out specific repository and branch 
        uses: actions/checkout@v2
        with:
          repo: https://github.com/vitechsystems/{{ github.event.inputs.repo_name }}.git
          ref: ${{ github.event.inputs.branch_name }}

      - name: Download Wiz CLI
        run: |
          curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 &&
          chmod +x wizcli

      - name: Authenticate to Wiz
        run: |
          ./wizcli auth-id "${{ secrets.WIZ_CLIENT_ID }}" --secret "${{ secrets.WIZ_CLIENT_SECRET }}"
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Run wiz CLI IaC scan 
        run: ./wizcli iac scan-path ${{ github.workspace }} --policy "$POLICY"
